### ISSUE TITLE
CloudFormation dependency issue for Internet gateways can cause 'kube-aws up' to fail

### ISSUE THREAD

**Issue by whereisaaron** [kubernetes-incubator/kube-aws#1077]
CloudFormation cannot implicitly work out that an IGW needs to be attached to a VPC before you can add a route to the IGW. If you are unlucky things happen in the wrong order and the stack creation fails.

You can see in this example below using kube-aws 0.9.9, CF attempts to add the route to the IGW to the RTB and fails, right before it actually attaches the IGW to the VPC.

```
+00:00:39	Controlplane	CREATE_COMPLETE         		SecurityGroupElbAPIServer
+00:00:39	Controlplane	CREATE_IN_PROGRESS      		MyClusterPublic2cRouteToInternet
+00:00:40	Controlplane	CREATE_COMPLETE         		MyClusterPublic2bRouteTable
+00:00:40	Controlplane	CREATE_FAILED           		MyClusterPublic2cRouteToInternet	"route table rtb-5bad0e33 and network gateway igw-160d2c7f belong to different networks"
+00:00:40	Controlplane	CREATE_IN_PROGRESS      		VPCGatewayAttachment  	"Resource creation Initiated"
+00:00:41	Controlplane	CREATE_IN_PROGRESS      		SecurityGroupWorkerIngressFromWorkerToWorkerKubeletReadOnly
```

According to [some forum discussion](https://forums.aws.amazon.com/thread.jspa?threadID=100750), this behavior is expected, and the fix is an explicit `DependsOn`:

>The problem is that Amazon only makes attaching internet gateway routes depend on the internet gateway, and not the internet gateway attachment.
>
> The issue is solved by adding "DependsOn": "your-internet-gateway-attachment" to every route adding that uses the internet gateway.

AWS said (in 2012, but I guess this hasn't changed):
>"We will document it - CloudFormation doesn't have knowledge of dependencies that are enforced by the services below it today."

**Comment by mumoshu** [comment]
Hi @whereisaaron! Good catch.
Just my two cents but probably the significant context in kube-aws here is that it doesn't try to modify existing AWS resources including a route table.
So, can we just add `"DependsOn": "theInternetGateway"` to the route-table created by kube-aws, rather than adding it to each route?
An existing route-table not created by kube-aws should have already been configured properly by the user including (the route to IGW|its attachment to the VPC) and therefore there would be no need to add the DependsOn to every route.

**Comment by whereisaaron** [comment]
@mumoshu I think they mean every route that is created by the CloudFormation stack to the IGW. In the case of a preexisting route table, there would be no route created (to be dependent on anything). The `ManageRouteToInternet` test should cover both situations.

You know the template and CF better than I, but from they description I don't think `"DependsOn": "theInternetGateway"` would work, because the dependency is considered met as soon as `theInternetGateway` is created, even though it is not attached to the yet (and so you can't add the route yet).

My guess is what you need is something like in `*InternetGatewayRouteLogicalName` to add `"DependsOn": "VPCGatewayAttachment"` ?

```
    {{if $subnet.ManageRouteToInternet}}
    ,
    "{{$subnet.InternetGatewayRouteLogicalName}}": {
      "Properties": {
        "DestinationCidrBlock": "0.0.0.0/0",
        "GatewayId": {{$.InternetGatewayRef}},
        "RouteTableId": {{$subnet.RouteTableRef}}
      },
      "Type": "AWS::EC2::Route",
      "DependsOn": [ "VPCGatewayAttachment" ]
    }
    {{end}}
```

**Comment by mumoshu** [comment]
> My guess is what you need is something like in *InternetGatewayRouteLogicalName to add "DependsOn": "VPCGatewayAttachment" ?

Thx for the suggestion!

It is really confusing but `VPCGatewayAttachment` is created only when the VPC is created by kube-aws as of today. Assuming we needed the modification, the CFN template snippet should look like:

```
    {{if $subnet.ManageRouteToInternet}}
    ,
    "{{$subnet.InternetGatewayRouteLogicalName}}": {
      "Properties": {
        "DestinationCidrBlock": "0.0.0.0/0",
        "GatewayId": {{$.InternetGatewayRef}},
        "RouteTableId": {{$subnet.RouteTableRef}}
      },
      "Type": "AWS::EC2::Route",
      {{if .VPCManaged}}
      "DependsOn": [ {{$.VPCGatewayAttachment}} ]
      {{end}}
    }
    {{end}}
```

However, if the VPC isn't managed by kube-aws i.e. it is provided by the user, the user must have already attached an IGW to the VPC. So, my guess is that there should be no need to add the DependsOn here.
Would this explanation sounds reasonable?

// Btw, perhaps it's true that I may know the CFN part of kube-aws more than someone but it doesn't really mean I can remember every part of it to decide things correctly because the world isn't really intuitive 😄 I always appreciate your support like this!

**Comment by whereisaaron** [comment]
Thanks @mumoshu, not sure you need that VPCManaged test?

I think that the only time you don't want the `DependsOn` is if the route table is a supplied one, and not one created by kube-aws?

Going by the template `cluster.yaml` comments, I interpreted it as saying:
1. If you supply your own route table then the Internet gateway and route table entry for it is your responsibility
2. If you just supply e.g. an empty VPC (you specify only vpc.id), `kube-aws` will create the subnets, IGW, and route tables for you

The [manual](https://kubernetes-incubator.github.io/kube-aws/advanced-topics/use-an-existing-vpc.html) is also not concrete on what specifying only vpc.id does. Does specifying a vpc.id in fact compell you to also specified a routeTableId (and/or routeTable.id for every defined subnet)? If so, maybe the `cluster.yaml` comments and manual should highlight that?

If specifying vpc.id does compel you to provide your out route tables, then `ManageRouteToInternet` will be false, so the `VPCManaged` test is unnecessary. If specifying just vpc.id still leaves kube-aws to create the route table and IGW, then you still want the `DependsOn`, so the `VPCManaged` test is unwanted.

Also not sure I am not confused now 😄
