### ISSUE TITLE
Missing a default StorageClass

### ISSUE THREAD

**Issue by mumoshu** [kubernetes-incubator/kube-aws#1085]
On a vanilla kube-aws cluster, creating a PVC doesn't automagically get a corresponding PV due to missing a default storage class:

```
Events:
  FirstSeen	LastSeen	Count	From				SubObjectPath	Type		Reason		Message
  ---------	--------	-----	----				-------------	--------	------		-------
  16m		1m		62	persistentvolume-controller			Normal		FailedBinding	no persistent volumes available for this claim and no storage class is set
```

I guess you can easily reproduce this by running `helm install stable/mysql`.

Can we just install [the default from the upstream]( https://github.com/kubernetes/kubernetes/blob/master/cluster/addons/storage-class/aws/default.yaml) by default?

**Comment by whereisaaron** [comment]
Sounds good to bootstrap with and AWS this StorageClass. But please don't put it in the controller addon manifest or label it 'addonmanager.kubernetes.io/mode=EnsureExists', or kube-aws users won't be able to change to a different default StorageClass (e.g. EFS or Glusterfs) without patching the cloudinit file.

**Comment by c-knowles** [comment]
Patching in the cloudinit is the way most other similar items are done, currently we have the same issue on tiller and many other items. I think we should keep it consistent or agree on an entirely new way to allow users to patch their cluster without it being overridden. As a minimum requirement we could allow the default here to be switched off.

**Comment by whereisaaron** [comment]
Good point, it is the only resource bootstrap method we have. It would be nice to be able to bootstrap some helpful but non-essential resources, but that are malleable after launch. Especially things you may might like to update or reconfigure with less effort than rolling the controller instances. Things like Dashboard, Tiller, default Storage Class. All great things to add up front by default, but for which we don't actually want to prevent updates or deletion.

Maybe `kube-aws` could create some of these resources via the API rather than dropping them in the 'manifests' folder?

Then we could add helpful stuff like deploying a helm nginx-ingress chart and 'hello world' app. Great for a new user experience, but trivially delectable when you don't need it.

But I agree @c-knowles, by all means add the default storage class to 'manifests', maybe with a cluster.yaml switch to disable it.

**Comment by weisjohn** [comment]
For those looking for a work around, after the render and install steps, I ran `kubectl apply -f https://raw.githubusercontent.com/kubernetes/kubernetes/e594b2c1215ddddff15b6502345f8a5938460d9e/cluster/addons/storage-class/aws/default.yaml` to create the default storage class in my cluster.

Then, I deleted and re-release my helm chart, and the PVs were created successfully.

@mumoshu or @whereisaaron if there's a better way, feel free to mention it. After reading the thread, I looked in the `cluster.yaml`, but didn't see anything.
