### ISSUE TITLE
Best practice of team operation

### ISSUE THREAD

**Issue by int128** [kubernetes-incubator/kube-aws#1122]
When two or more people operate a cluster, how should we share the cluster information? At least it needs `kubeconfig` and `credentials` to connect to the cluster, but `credentials` is excluded from the Git repository by default (yup, it is secret!). Would you tell me your best practice?

It would be more helpful if the best practice is described in the document. For your reference, kops shows [the way to share the cluster information](https://github.com/kubernetes/kops/blob/de6d4e69f58c33933e9aa35c91a04e17e3cc7677/docs/kubectl.md).

Thanks for the great work.

**Comment by whereisaaron** [comment]
Best idea is probably not to use certificates at all, since you can't (currently) revoke them. You can instead e.g. [install `dex`](https://github.com/kubernetes-incubator/kube-aws/tree/master/contrib/dex) and the people using the cluster can then authenticate against e.g. LDAP, Google, or github.

On the other the hand certificates are much easier to set up. You can sign additional certificates for other user names, and then set RBAC permissions in your cluster to decide what those users can do. E.g. this `openssl` script will create a `aloy.pem` and `aloy-key.pem` for user `aloy`.

```
#!/bin/bash
# Generate key and cert for each user, sign with root cert, remove temp files
set -e

# Must be run in credentials folder
create_user()
{
  local u="$1" orgs="$2" days="$3"
  local subject="${orgs}/CN=${u}"

  if [[ -z "$days" ]]; then
    days=365
  fi

  if [[ ! -f ${u}.pem ]]; then
    echo "Creating ${u}.pem for $subject ($days days)"
    openssl genrsa -out ${u}-key.pem 2048
    openssl req -new -key ${u}-key.pem -out ${u}.csr -subj "$subject" -config additional-users-openssl-config.cnf
    openssl x509 -req -in ${u}.csr -CA ca.pem -CAkey ca-key.pem -CAcreateserial -out ${u}.pem -days $days -extensions v3_req -extfile ../additional-users-openssl-config.cnf
    rm ${u}.csr ca.srl
  else
    echo "${u}.pem already exists"
  fi
}

umask 0077

create_user aloy "/O=mycompany" 365
```

`additional-users-openssl-config.cnf`:
```
[req]
req_extensions = v3_req
distinguished_name = req_distinguished_name
[req_distinguished_name]
[ v3_req ]
basicConstraints = CA:FALSE
keyUsage = digitalSignature, keyEncipherment
extendedKeyUsage = clientAuth
```

Then you can create a `kubeconfig` file for each user, embedding their certificate directly in their e.g. `kubeconfig-aloy` file. Then that is all they need. They can run e.g. `kubectl --kubeconfig=kubeconfig-aloy get pod` or move the file to `~/.kube/config` and run `kubectl get pod`.

```
#!/bin/bash
# Create kubeconfig files for each user

cluster=mycluster
endpoint=https://${cluster}.example.com
kc=kubectl

for u in aloy; do
  export KUBECONFIG=${u}-kubeconfig
  touch $KUBECONFIG
  echo "Creating $KUBECONFIG"
  $kc config set-cluster $cluster --certificate-authority="credentials/ca.pem" --server="${endpoint}" --embed-certs=true
  $kc config set-credentials $u --client-certificate="credentials/${u}.pem" --client-key="credentials/${u}-key.pem" --embed-certs=true
  ns=default
  $kc config set-context "${u}-${ns}" --cluster $cluster --user=$u --namespace=$ns
  $kc config use-context "${u}-${ns}"
done
echo "Done."
```

**Comment by whereisaaron** [comment]
That `kops` example is just exports the the admin (cluster root) user to give it to everybody! If that is all you want you can just embed the `admin` user certificate out of `credentials` into the `kubeconfig` file. Then you can give `kubeconfig-admin` to people.

```
kubectl config view --flatten --kubeconfig=kubeconfig > kubeconfig-admin
```

**Comment by mumoshu** [comment]
@int128 @whereisaaron Thanks for bringing this up 👍 

I'm not yet sure if there's a single best way to share credentials for teams, but both delegation and exporting method would serve certain use-cases. Thanks for the info, @whereisaaron!

In addition to the info, I'd suggest including a kubectl wrapper like this:

```
#!/usr/bin/env bash

export KUBECONFIG=kubeconfig.tmp
export SOPS_KMS_ARN="arn:aws:kms:$region:$account:key/$id"

# To not leave sensitive information unnecessary long
function finish {
  rm "$KUBECONFIG"
}
trap finish EXIT

sops -d kubeconfig.enc > "$KUBECONFIG"

kubectl "$@"
```

so that you can safely(if u think so!) git-commit the encrypted kubeconfig and the wrapper to share credentials to access your cluster.

Also note that you should not ever store persistent AWS credentials in your local disk, ever give unnecessary party the KMS key access, ever allow someone to create AWS session without MFA.

Example file-tree:

- `<project root>/`
  - `clusters/`
    - `<your cluster name>`/
      - `kubeconfig.enc`
      - `bin/kubectl`

**Comment by mumoshu** [comment]
Regarding the q about how to share not only api access but the whole `credentials/` contents with teams, I'm considering to encrypt all the `-key.pem` files and `token.csv` via a wrapper like I've suggested for kubeconfig.

I'll share it once I came up with an reusable script myself, but appreciate it if anyone could share one 😃

**Comment by whereisaaron** [comment]
Or, @mumoshu if `kube-aws` could help people bootstrap `dex` (or similar) against common auth providers (e.g. github, google) then admins could avoid sharing any static credentials!

**Comment by mumoshu** [comment]
@whereisaaron Would the contrib doc written thanks to @camilb would help?

 https://github.com/kubernetes-incubator/kube-aws/tree/master/contrib/dex?

FYI, I'm planning to use heptio/authenticator for sharing limited access to the cluster for my devs/ops colleagues.

Also, btw, I'd still like to share my admin credentials with very few people so that we as a team won't lose privileged access to the cluster when we broke dex/authenticator and I get hit by a truck at the same time 😉

**Comment by whereisaaron** [comment]
That @mumoshu I already found @camilb's excellent contribution and we discussed linking it into the `kube-aws` docs under 'Add-ons'. The next step to make `dex` a `kube-aws` supported add-on.

`heptio/authenticator` looks excellent for cluster admins, but it relies on all users having IAM accounts (or delegated), so `dex` seems a bit more flexible for access for users just deploying workloads?

**Comment by int128** [comment]
Thank you for the replies.
I think it may be happy if the doc covers the following topics in the future.

- Daily cluster operation using each account
  - Authentication and RBAC with dex or heptio/authenticator
  - How to join a new member to the team (i.e. how to configure kubectl)
- Cluster admin (such as changing `kube-aws` config or redesign AWS components)
  - How to share cluster admin credentials safely

**Comment by mumoshu** [comment]
@whereisaaron I'm willing to accept any PR related to dex support!

Anyway, I'm a bit opinionated about this. For me, `heptio/authenticator` is generally better in the sense that every environment I've worked for had devops who needs access to AWS for their work. K8S on AWS is just an addition to their ability to manage infrastructure things.

**Comment by mumoshu** [comment]
@int128 Thanks for the feedback! I'll add those to the docs once I come up with something.
I'd be happier if someone contributes any of those, hopefully 😉

**Comment by mumoshu** [comment]
And [here's a general-purpose mozilla/sops wrapper I churned out yesterday](https://github.com/mumoshu/sops-vault) to transparently encrypt/decrypt `credentials/*-key.pem` before and after running any kube-aws command.
Would help doing some GitOps.

**Comment by whereisaaron** [comment]
Regards `dex`, @nabadger and I have paired it with a web UI `dex-k8s-authenticator` project and written helm charts for both. @camilb, I think the charts are flexible and should work for your example use case.

The `dex-k8s-authenticator` web UI makes it easy for users/admins to configure `kubectl` for a cluster using OIDC+dex. It authenticates you with the upstream IDP and then give you the `kubectl` commands needed to install your token/refresh.

The 'dex-k8s-authenticator' project:
https://github.com/mintel/dex-k8s-authenticator

The `dex` and `dex-k8s-authenticator` charts (instructions included):
https://github.com/mintel/dex-k8s-authenticator/tree/master/charts

## Installing dex with web UI for configuring 'kubectl'
```
git clone git@github.com:mintel/dex-k8s-authenticator.git
helm inspect values charts/dex > dex.yaml
helm inspect values charts/dex-k8s-authenticator > dex-k8s-authenticator.yaml
```
Edit the values files for your environment and requirements (`dex.yaml` and `dex-k8s-authenticator.yaml`). 

Create the DNS names for your `dex` (e.g. 'dex.example.com') and `dex-k8s-authenticator` (e.g. 'login.example.com') pointed at the ingress controller you are using. Be sure to enable HTTPS. You can install [`cert-manager`](https://github.com/jetstack/cert-manager) to automatically issue Lets Encrypt certificates.

You also need to configure each Kubernetes cluster to use `dex` at e.g. 'dex.example.com' by [setting the OIDC parameters for the Kubernetes API server](https://kubernetes.io/docs/admin/authentication/#openid-connect-tokens). This is easy using the [`kube-aws` installer](https://github.com/kubernetes-incubator/kube-aws/tree/master/contrib/dex).

```
helm install --namespace dex --values dex.yaml charts/dex
helm install --namespace dex --values dex-k8s-authenticator charts/dex-k8s-authenticator
```
Navigate to https://login.example.com and follow the instructions to authenticate using `dex` and configure `kubectl`.
