### ISSUE TITLE
Feature: Rescheduler add-on

### ISSUE THREAD

**Issue by c-knowles** [kubernetes-incubator/kube-aws#118]
Do we want to support the [rescheduler add-on](http://kubernetes.io/docs/admin/rescheduler/) out of the box? Useful links - [k8s](https://github.com/kubernetes/kubernetes/pull/30870), [kops](https://github.com/kubernetes/kops/issues/355)

**Comment by mumoshu** [comment]
@c-knowles Thanks for bringing this up 👍 

Yes. I even believe it should be enabled by default.

**Comment by pieterlange** [comment]
Lets feature (experimental) flag it first

**Comment by mumoshu** [comment]
Note: [Rescheduler e2e test](https://github.com/piosz/kubernetes/blob/4a6123df0aceff6ae9e5522c836d62128782250c/test/e2e/rescheduler.go) should be run against kube-aws created clusters in https://github.com/coreos/kube-aws/tree/master/e2e

**Comment by mumoshu** [comment]
@c-knowles Do you have any time to address this?

**Comment by c-knowles** [comment]
Yes, can do. What's kube-aws's philosophy when it comes to which add-ons we install? For example, I'd like to add [kube-state-metrics](https://github.com/kubernetes/kube-state-metrics) too plus some of the [others](https://github.com/kubernetes/kubernetes/tree/master/cluster/addons) maybe even using the add-on manager. We can likely add all that but make them optional where k8s doesn't require it to run (the DNS is an add-on but most people will expect it to be running since the k8s docs list how to use it and say it's built in)

**Comment by mumoshu** [comment]
I'd like to keep kube-aws focused on:

* High availability
* High scalability
* Security
* Flexibility

Accordingly, I'd like to provide special treatment(e.g. can be enabled easily via `cluster.yaml`) for addons like rescheduler because it allows users achieve high availability, one of the focuses of kube-aws.

For addons don't directly contribute to scalability, availability and security, I'd like not to support them specially in e.g. cluster.yaml but rather provide a way to provide arbitrary addons to be installed during `kube-aws up`.

It would be something like `addons/` directory under kube-aws state directory to which an user feed arbitrary manifest yaml files.

**Comment by mumoshu** [comment]
Btw, if you like the idea of `addons/` directory, I can submit a pull request containing the PoC for it.

**Comment by c-knowles** [comment]
If we do the add-ons directory I think we should use the add-on manager as that seems to be the normal way to do this in k8s.

**Comment by mumoshu** [comment]
Yes.

IMHO moving to addon-manager instead of curl is a pretty orthogonal change though, because we already have a directory to place manifest files for addons like kube-dns in controller nodes.

To be clear, I guess we could support the local `addons` dir to be used for uploading user-provided manifest files to the remote addons dir, and then possibly in a separate issue we can move to use addon-manager for deploying all the addons(including the default ones with user-provided ones) from the remote dir.

**Comment by c-knowles** [comment]
@mumoshu I restarted this one but I need some help to get the e2e tests running properly.

How can I run a specific test or just the k8s conformance tests? (time saver while I develop). Seems to be `DOCKER_REPO=quay.io/mumoshu/ SSH_PRIVATE_KEY=path/to/private/key ./e2e run conformance`? Should I update DOCKER_REPO to my own? It's not clear to me what that part is actually doing. First time around I updated it to my own by it seems to be more a registry than a repo as the tests append `kube-e2e` to it and expect it to always have a trailing slash. If I should be changing it to my own, do you know which repos are required so I can pre-create them?

**Comment by c-knowles** [comment]
@mumoshu do you have any feedback on how to successfully perform conformance tests?

**Comment by mumoshu** [comment]
Sorry I missed your comment here!
Would you mind trying the `FOCUS` env var for running only part of tests like:

```
FOCUS='.*support.*a.*client.*no.*Conformance.*' KUBE_AWS_CLUSTER_AUTOSCALER_ENABLED=1 KUBE_AWS_AWS_NODE_LABELS_ENABLED=1 KUBE_AWS_NODE_LABELS_ENABLED=1 KUBE_AWS_WAIT_SIGNAL_ENABLED=1 KUBE_AWS_AWS_ENV_ENABLED=1 KUBE_AWS_USE_CALICO=true KUBE_AWS_CLUSTER_NAME=kubeawstest4 sh -c './run all'
```

The content of `FOCUS` is originating from `ginko.focus=<pattern>` in https://github.com/kubernetes/community/blob/master/contributors/devel/e2e-tests.md#building-and-running-the-tests
However please beware that `'` and `"` in the `FOCUCS` env var won't be encoded/decoded properly so try to use `.*` or `.+` to match suspicious characters.

Also FYI https://github.com/coreos/kube-aws/pull/124#issuecomment-270855103

You can use `./run conformance` instead of `./run all` to just re-run conformance tests against the cluster already created previously with `./run all`.

**Comment by c-knowles** [comment]
@mumoshu No problem, just want to get started 👍 Do you know if it's possible to use ECR for the repo? I tried it for `DOCKER_REPO` but it seems this is a repo name prefix and there are various appends.

**Comment by mumoshu** [comment]
@c-knowles Haven't tried yet but probably possible once you provide `DOCKER_REPO=name/of/your/docker/repo/hosted/by/ecr` and you run `docker login` in all the controller nodes as described in http://docs.aws.amazon.com/cli/latest/reference/ecr/get-login.html

**Comment by redbaron** [comment]
reading code (https://github.com/kubernetes/kubernetes/blob/7028abc5fcb41e7975b98f0900d5765afc48f464/pkg/features/kube_features.go#L65-L68)  it looks like  enabling `ExperimentalCriticalPodAnnotation`  kubelet feature can take us a long way even without rescheduler

**Comment by c-knowles** [comment]
I wonder what the difference is supposed to be and the general plan in k8s. Anyway, I'm still going to go ahead and implement something here.

**Comment by c-knowles** [comment]
Quick update, I have this running in a cluster using v0.9.4. Getting it running was pretty easy so far. I've done a quick test by filling a cluster with requests for large amounts of memory. Then I deleted the only instance of heapster:
```
I0307 15:33:31.587742       6 rescheduler.go:114] Critical pod kube-system_heapster-v1.2.0-4088228293-1l9w4 is unschedulable. Trying to find a spot for it.
I0307 15:33:31.597440       6 rescheduler.go:128] Trying to place the pod on node ip-10-0-18-16.eu-west-1.compute.internal
I0307 15:33:31.645617       6 rescheduler.go:258] Pod OBFUSCATED will be deleted in order to schedule critical pod kube-system_heapster-v1.2.0-4088228293-1l9w4.
I0307 15:33:31.645837       6 event.go:216] Event(api.ObjectReference{Kind:"Pod", Namespace:"kube-system", Name:"OBFUSCATED", UID:"cef393b6-fcaf-11e6-bde0-061767539449", APIVersion:"v1", ResourceVersion:"401845", FieldPath:""}): type: 'Normal' reason: 'DeletedByRescheduler' Deleted by rescheduler in order to schedule critical pod kube-system_heapster-v1.2.0-4088228293-1l9w4.
I0307 15:33:31.674114       6 rescheduler.go:147] Waiting for pod kube-system_heapster-v1.2.0-4088228293-1l9w4 to be scheduled
I0307 15:33:33.677614       6 rescheduler.go:159] Pod kube-system_heapster-v1.2.0-4088228293-1l9w4 was successfully scheduled.
I0307 15:33:41.674342       6 rescheduler.go:204] Releasing taint {Key:CriticalAddonsOnly Value:kube-system_heapster-v1.2.0-4088228293-1l9w4 Effect:NoSchedule} on node ip-10-0-18-16.eu-west-1.compute.internal
I0307 15:33:41.681705       6 rescheduler.go:222] Successfully released all taints on node ip-10-0-18-16.eu-west-1.compute.internal
```

I've yet to run the e2e tests and still struggling to get those to run to completion.

@mumoshu few things worth noting:
1. It seems we should deployed via Pod, I'm assuming that's ok for now to match the others like the scheduler/apiserver etc that run on the controller nodes.
1. We have a mixture of hyperkube images and gcr.io images specific to binary, I'm going with gcr.io as that's what the salt config has. I'm not sure why we use both other than historic reasons?
1. For log output, most configs I have seen routes to files in `/var/log/`. However the current kube-aws setup seems to be stdout/stderr so I will align to that for now. We did allow `.Experimental.AuditLog.LogPath` to be specified but I don't know why, any ideas? Some of that was in https://github.com/coreos/kube-aws/pull/92. We may need to separate these logs at some point in order to parse and index them more easily; or we assume everyone has something downstream which matches container names/log formats against a known list of formats for everything that gets piped through. I would tend to go with the same setup as k8s core which seems to be `/var/log/` files for these core components, although not sure if that situation is changing with self hosted.

**Comment by c-knowles** [comment]
v0.2.2 is done on master. v0.3.0 version is needed for k8s v1.6. I've upgraded locally and mostly working apart from the logs for which I've filed https://github.com/kubernetes/contrib/issues/2518.

**Comment by c-knowles** [comment]
I've submitted https://github.com/kubernetes-incubator/kube-aws/pull/787 to finish this work off then we can close this.

**Comment by c-knowles** [comment]
PRs all merged to master, covered by next release which should be v0.9.8-rc.1
