### ISSUE TITLE
[Proposal] Disable CoreOS update-engine

### ISSUE THREAD

**Issue by jorge07** [kubernetes-incubator/kube-aws#1240]
We're having some issues due to CoreOS update-engine. Some machines has been upgraded to a newer CoreOS version. Immutability is important and this is causing upgrades to docker `17.09.1-ce` that has serious issues like: #1135

**Comment by jorge07** [comment]
I'm also thinking about a mapping of `kubernetes version` - `CoreOS Release`.

The main reason is follow the trusted versions of the official changelog and throw and warn if the coreOS release doesn't have the requirements:

https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG-1.8.md#external-dependencies
https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG-1.9.md#external-dependencies

In the other hand it will require a periodic maintenance of this mapping.

**Comment by Fsero** [comment]
what about security updates then? can we somehow downgrade or pin versions while keeping base OS security updates?

**Comment by jorge07** [comment]
It's how it is right now. I made a PR doing a feature flagging to remove auto updates. 

Security updates are important but if they came with a downtime in my cluster I prefer to live in the risk during some time or add my own patch. In the other hand I prefer run a cluster update to patch a security issue, otherwise I'm broking immutability and running in issues like my current problem: 

Right now I've a node pool in my cluster with 2 versions of docker running (1.12.1 & 17.09.1-ce) because a machine restarted after a coreOS update and I think this is a high risk I can't asume, half of my elastic cluster is down because of this.

**Comment by jorge07** [comment]
Related: https://github.com/kubernetes-incubator/kube-aws/issues/1209

**Comment by mumoshu** [comment]
Thanks for bringing this up!

Just to be clear, I believe that you normally don't receive automatic updates as of today, already. 
Please see my comment at https://github.com/kubernetes-incubator/kube-aws/pull/1241#pullrequestreview-112640826. TL;DR; We do miss disabling the update-engine, but we do have `reboot-strategy: off`. It practially worked like "updates are downloaded but never applied automatically".

Anyway, your change made in #1241 makes a lot of sense 😉I just wanted to make sure I'm not missing anything here.

**Comment by jorge07** [comment]
@whereisaaron this is why I did #1201. The current issue it's that even with amiId setted some workers where updated. We are going to investigate the reasons of the reboot of some random machines. But for example, an aws maintenance reboot can potentially crash your node pool. We're also going to upgrade de docker 17.12, but also considering a dockerless cluster.

**Comment by cmcconnell1** [comment]
Hello All, 

FWIW, I have been pinning our 'amiId' for over a year now with most of our kube-aws clusters.   I believe it's allowed our older clusters (sadly some are over a year old) to be more stable given everything you've noted above. 
 
I initially started 'pinning' the amiId because I experienced intermittent strange/blocking issues after initializing a new (say Dev for example) cluster.  After deploying the initial cluster, and copying the new cluster config data (and changing names and subnet CIDR, etc.) to create a stage/prod cluster, the second cluster provisioning would fail with strange errors--this cluster had the exact same configs (just different names and subnets, etc) as the one that just deployed without any issues.  'Tracked it down to the CoreOS AMI incrementing in the time between a deploying a Dev cluster and a Stage cluster.  So even though I had checked the initial new cluster's config files into git, it could not be redeployed--due to the CoreOS AMI version being incremented behind the scenes.

It's great to see these issues discussed here, it's very helpful for me because when we've seen strange issues in the past, I wasn't sure what happened.  And I noticed that on our most recent kube-aws cluster upgrade ( v0.9.10-rc.3 ) that ami pinning is now the default and I wanted to ask about that.

Thanks!

**Comment by Quentin-M** [comment]
We had a little scare last week when Container Linux was updated and almost broke our fleet.. thought it'd be relevant to share here https://blog.quentin-machu.fr/2018/11/12/the-moment-container-linux-was-updated-and-almost-broke-our-fleet/
