### ISSUE TITLE
Stop relying on the apiserver insecure port for control plane components and bootstrapping

### ISSUE THREAD

**Issue by danielfm** [kubernetes-incubator/kube-aws#1291]
There are several control plane components (i.e. controller manager, scheduler, etc) and bootstrapping tasks (i.e. systemd `ExecStartPre`s, `kube-node-label`, etc) on `userdata/cloud-config-controller` still relying on apiserver's insecure port.

Aside from being a security concern, the insecure port binding in apiserver is deprecated and will soon be removed.

**Comment by davidmccormick** [comment]
Hi

There are a number of systemd service scripts that use the insecure port including install-kube-system so we must be careful to give them a certificate they can use before disabling the port.  I only mention this because I have implemented a new systemd service that assumes it can use the insecure port! :)
