### ISSUE TITLE
kube-aws validate fails with an IAM account that has full access

### ISSUE THREAD

**Issue by kylesloan** [kubernetes-incubator/kube-aws#1442]
I am trying to determine what level my kube user needs in IAM in order to perform the actions needed.

```
kube-aws validate

WARNING: You will not be able to upgrade your cluster to future kube-aws releases (0.11+) without changing your cluster network settings.
Please consider updating your cluster with Kubernetes.Networking.SelfHosting enabled to allow updates (the networking update does incure some minor cluster downtime/disruption as it rolls out so please do read the docs in the default cluster.yaml)

Validating UserData and stack template...
Validation Report: {
  Capabilities: ["CAPABILITY_NAMED_IAM"],
  CapabilitiesReason: "The following resource(s) require capabilities: [AWS::CloudFormation::Stack]",
  Description: "kube-aws Kubernetes cluster quick-start-k8"
}
{
  Capabilities: ["CAPABILITY_IAM"],
  CapabilitiesReason: "The following resource(s) require capabilities: [AWS::IAM::ManagedPolicy]",
  Description: "kube-aws Kubernetes cluster quick-start-k8"
}
{
  Capabilities: ["CAPABILITY_IAM"],
  CapabilitiesReason: "The following resource(s) require capabilities: [AWS::IAM::ManagedPolicy]",
  Description: "kube-aws Kubernetes node pool quick-start-k8 nodepool1",
  Parameters: [{
      Description: "The name of a control-plane stack used to import values into this stack",
      NoEcho: false,
      ParameterKey: "ControlPlaneStackName"
    }]
}
stack template is valid.

Validation OK!
```

I tried many different AMI policies and could not get past this, and up also failed for me in different ways.  I finally made a policy of

```
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Action": "*",
      "Resource": "*"
    }
  ]
}
```

And still got the same errors on validation, but up seemed to work.

It would be nice if the README listed what roles the IAM should have.

**Comment by kylesloan** [comment]
FYI I was following https://github.com/kubernetes-incubator/kube-aws/blob/master/docs/tutorials/quick-start.md

**Comment by mumoshu** [comment]
@kylesloan Hi!
Your `kube-aws validate` seems to indicate that it is passing. Perhaps you're sharing wrong logs?

**Comment by kylesloan** [comment]
Correct, it throws errors but still lets me run.  This is very confusing, as I spent 20 minutes trying different levels of IAM and then just tried to run the stack up, which worked.  It would be nice to list the IAM recommended levels.

**Comment by mumoshu** [comment]
@kylesloan Sorry for making you frustrated and wasting your 20 minutes.

There has been several similar requests, but no one had tried to contribute the working set of minimum iam policies. Personally, I'm using a ["cloudformation service role"](https://github.com/kubernetes-incubator/kube-aws/commit/cc045b41a5ad79c78f4c1d1f5904dcf62d056185), so that you don't need broad range of permissions in your own iam user/role. Would it work for you, too?

If not, probably you can use CloudTrail to record all the API calls made by your IAM user while kube-aws  and CloudFormation are running. It will help you decide which permissions are required for your use-case.

Also, kube-aws won't be able to provide the single set of required permissions. You might have asked which IAM permissions kube-aws requires. But it highly depends on what you instruct kube-aws (and hence CloudFormation) to manage.

**Comment by kylesloan** [comment]
Closing out, I went with eksctl instead

**Comment by mumoshu** [comment]
@kylesloan Thanks for the info!
Just curious, but how did eksctl solve this exact issue? I was also considering to merge our efforts with eksctl but was unable to figure out at that time how eksctl supports edge cases like this.

**Comment by kylesloan** [comment]
Honestly I'm not sure, its one of those things "that just worked".  I think it uses my personal AWS account settings and not a "system/kube" type of of user.  You do not need to setup an account in IAM for kube.

**Comment by mumoshu** [comment]
@kylesloan Thanks a lot for the response.

Ah okay I think I figured it out.

You probably had almost full access to AWS APIs. So k,ube-aws should not have reported validation errors like you've encountered.

`kube-aws` was reporting invalid validation errors because it was missing capabilities like `CAPABILITY_NAMED_IAM` and `CAPABILITY_IAM` in validations, but not in `up`s.  Both `kube-aws` and `eksctl` requires those caps, and you do have them permissions to use those, hence `kube-aws up` and `eksctl create` both worked. So, this seems like a bug in kube-aws! Thanks for catching it.

Btw, for what it worth, eksctl doesn't do cloudformation stack template validation. So if you are to do complex customizations to your k8s on aws cluster, kube-aws would provide an additional operational safe-guard.

Cheers!
