### ISSUE TITLE
Migration instructions from coreos-kubernetes kube-aws

### ISSUE THREAD

**Issue by felixbuenemann** [kubernetes-incubator/kube-aws#154]
It would be great if there were some instructions on how to upgrade from the old `kube-aws` from coreos/coreos-kubernetes to this new version.

**Comment by pieterlange** [comment]
I'm not sure if there's a clean upgrade path from the old kube-aws.

The safest method i can recommend is to build a new cluster and migrate the kubernetes resources with something that looks like `kubectl get $resource -o yaml | kubectl create --kubeconfig=kubeconfig-new-cluster -f -`. In depth guide for this: https://coreos.com/kubernetes/docs/latest/cluster-dump-restore.html

**Comment by mumoshu** [comment]
I'd generally recommend the way @pieterlange described for updating kube-aws and the clusters created with it.

The reasoning behind it is that because a safe cluster upgrade could be done only out of band from the current kube-aws scope. For extreme example, replacing the whole AWS resources managed by CloudFormation could always result in some downtime. `kube-aws update` is meant to be used for updating part of a cluster, not the whole. Newer kube-aws release could result in significant change in its underlying implementation = organization of AWS resources inside a cfn stack.

Creating a new kube-aws cluster and then switching to it could always be safer because then we can roll-back if the new cluster isn't functioning correctly. This is true regardless of how kube-aws changes its underlying implementation over time.

**Comment by felixbuenemann** [comment]
Thanks for the advice.

Would you like to keep the issue open to track documentation changes or can it be closed?

**Comment by mumoshu** [comment]
@felixbuenemann Thanks for your confirmation 👍 
I'd like this to be open until we add documentation about it.

**Comment by iam404** [comment]
Hi @mumoshu @pieterlange 
I was thinking if there is any possible way we can migrate/move EBS volumes or persistentvolumes attached to old cluster to new kube-aws cluster, if creating new cluster is the only way to update kube-aws.

**Comment by redbaron** [comment]
@iam404  there is an cluster autosave feature: https://github.com/kubernetes-incubator/kube-aws/blob/6a7bc0ec07cb6a698af1dc45f861c7aedbacaea8/Documentation/kubernetes-on-aws-backup.md you can then use restore script to "import" resource back into new cluster.

Also I'd like to note that creating new cluster is the only way officially support due to lack of automated upgrade tests, not because it is not possible. In my experience clusters can be upgraded smoothly inplace in most of the cases.

**Comment by iam404** [comment]
@redbaron Thanx for the info.
But doc `kubernetes-on-aws-backup.md ` seems to be added 3 month ago. We are kinda stuck with kube-aws version `v0.9.1` . So will this `kubeResourcesAutosave:` work with `v0.9.1`.

We actually tried upgrading kube-aws inplace but it looks like new cluster was not able to connect to etcd cluster and some services like flanneld did not came up. So had to revert back to old.

**Comment by redbaron** [comment]
big jumps are less likely to succeed and it is true that some changes are leading to incompatible clusters.

What you can do is check the backup script which `kubeResourceAutosave` runs and run it yourself, then restore status to a new cluster.

Basically way to transfer volumes is to save `PersistentVolumeClaim` (PVC), `PersistentVolume` (PV) resources. Once imported new cluster "learns" about EBS volumes. Then you either restore StatefulSet's which then "discover" existing PVCs or just deploy your apps again, if all names and labels remain the same, then you should be good to go.

**Comment by c-knowles** [comment]
We have a little bit of experience with PVs/PVCs and EBS but it's mostly manual right now. A few notes I have that could be useful:
1. Ensure in the old cluster you mark the PV `persistentVolumeReclaimPolicy` as `Retain` otherwise they will get deleted or wiped when disconnected from the old cluster
1. Add the PVs and PVCs to the new cluster using an export (either the backup of kube-aws or kubectl get --export works also)
1. Delete the PVCs from the old cluster, the PVs should in theory then be `Released` status
1. Delete the PVs from the old cluster, they should detach from the instances automatically
1. Trigger an event on the new cluster that would cause a PVC/PV to be discovered/actioned, often for us this means deleting a Pod that is reliant on the PVC which then seems to cause the PVC to bind and the PV to attach to the instance. There's some subtleties here in which AZs you are running in as the instance needs to be in the same AZ as the PV and subsequently the Pod also needs to go there. Most of that is taken care of by k8s but I have seen a few occasions where we had to terminate the Pod a few times to get it all connected back up properly.

I'm considering using EFS in many cases because multiple instances+AZs can connect to it and hence the switchover can be a lot smoother than this.

**Comment by redbaron** [comment]
Doesn't EBS detachment happens when PVC detaches from from POD? therefore it is enough do delete pods, and controller managing them , but do it with cascading=false
