### ISSUE TITLE
Windows worker node support

### ISSUE THREAD

**Issue by paalkr** [kubernetes-incubator/kube-aws#1546]
I know this is a long-shot, but I would like to get a discussion going. What would it take to add support for Windows nodes that are able to run .Net Framework apps? We do have some old apps that for various reason cannot be rewritten to .Net core, but still would like to migrate them to Kubernetes (as most of our services and apps now runs there).

https://docs.microsoft.com/en-us/dotnet/standard/modernize-with-azure-and-containers/modernize-existing-apps-to-cloud-optimized/deploy-existing-net-apps-as-windows-containers

https://kubernetes.io/docs/getting-started-guides/windows/

PS, we could probably contribute with dev resources to get this going if it's of any interest, and if it from a technology perspective is actually possible. 

Regards

**Comment by paalkr** [comment]
No one interested?

**Comment by davidmccormick** [comment]
Hi, I’m afraid that I have no bandwidth for looking into this option. Is this something you could code and I can then review?

**Comment by paalkr** [comment]
We might contribute with dev resources if there any interest in this. But we should first establish if it's even possible given the current kube-aws architecture.

Can we keep the issue open? I can close it later if we don't find internal resources that can contribute.

**Comment by dominicgunn** [comment]
This sounds interesting, we have some potential use cases on this side too, but unsure if we could commit resource to this right now.

**Comment by paalkr** [comment]
My colleague @andersosthus has started working on this, and we do have a windows worker node attached to one of our dev clusters. Bare in mind that this is in an extremely early stage, and there are many things that don't work.

**Comment by andersosthus** [comment]
As @paalkr said, I've started doing some POCs around this. Currently a bit on hold, since we need k8s 0.14 and we haven't upgraded the test cluster yet.

But some parts of the work needed is pretty clear already. We'll have to provide custom userdata scripts, possibly a custom assets file (since cloudinit is not a thing in Windows land) and stuff like that.

Maybe we could solve those as plugins? I'm not sure about how far along the plugin model is, or if kube-aws wants to have this in master alongside maintaining it?

**Comment by andersosthus** [comment]
Just a quick update. We've started working on this again and have a Windows node joined to the kube-aws created cluster.

We're now investigating how to best integrate it into kube-aws so that we can use kube-aws to manage the Windows part as well.

My initial thought is to see if I can do everything I need as a plugin.

**Comment by norkhairi** [comment]
Just wondering what's the status on this as I'd like to see this supported as well.

**Comment by andersosthus** [comment]
Due to the holidays and such it got delayed a bit, but I've started working on a few PRs against master that will start to incorporate this.

**Comment by dominicgunn** [comment]
Is this something you guys are still working on @andersosthus?
