### ISSUE TITLE
Terraform support

### ISSUE THREAD

**Issue by johanneswuerbach** [kubernetes-incubator/kube-aws#180]
While CloudFormation just works on AWS, having an option to export the stack as [terraform](https://www.terraform.io/) files would be great.

Would you be open to support multiple exports or are there even already plans to add a terraform exporter?

**Comment by pieterlange** [comment]
For now this is an explicit non-goal. Kops does terraform though: https://github.com/kubernetes/kops/

**Comment by johanneswuerbach** [comment]
Sadly kops doesn't support CoreOS yet, so now we need to choose :-(

**Comment by jgmize** [comment]
There are other choices as well: see https://github.com/kz8s/tack for a Terraform+CoreOS+k8s example, and there are others linked in its README.

**Comment by mumoshu** [comment]
@johanneswuerbach Hi, thanks for your interest on kube-aws!

From a maintainer/developer's pespective, kube-aws won't be supporting Terraform as it does complicate kube-aws while kube-aws's functionality converging to what can be achieved with the GCD of CloudFormation and Terraform(they're not interchangeable).

But anyways, could I ask you why you wanted kube-aws to support Terraform?

More concretely, does utilizing:
* `kube-aws up --export` and [Terraform's `aws_cloudformatinon_stack` resources](https://www.terraform.io/docs/providers/aws/r/cloudformation_stack.html)
* and/or `kube-aws`'s capability to deploy your kubernetes cluster to an existing VPC managed by Terraform

work for you?

**Comment by mumoshu** [comment]
@johanneswuerbach Any chance you could leave another feedback on this? :bow:

**Comment by johanneswuerbach** [comment]
Sorry @mumoshu, I missed the last notification.

While both solutions work for us, they don't really integrate into the existing landscape and require to hardcode several values inside the cloudformation template like VPCs, Route53 hosted zone. It also doesn't allow to manage the resources inside the template with terraform (e.g. to setup additional instance monitoring).

Overall I think having first-class tf support would be nice to have, but isn't blocking. I'm currently rendering the template and then translate the output manually into our terraform setup, which works well, just feels a bit too manual.

**Comment by mumoshu** [comment]
Thanks for the additional info @johanneswuerbach, it really help me understand the problem deeper.

I guess your problem could be partly resolved in an different form:

* If you'd like to stop values hard-coded into the cfn template, @icereval is [work is in progress](https://github.com/coreos/kube-aws/pull/195) for that. With his work, you could provide cfn params via terraform to specify which vpc, subnet, nat gateway, etc to be used to deploy an kube-aws cluster into an exsiting vpc managed by terraform. I'd appreciate it if you could confirm that all the values you care about are addressed or missed in the pr.
* For management of resources inside the cfn stack, you could raise feature requests for kube-aws to allow customization e.g. additional instance monitoring.

**Comment by mumoshu** [comment]
JFYI:

> * If you'd like to stop values hard-coded into the cfn template, @icereval is [work is in progress](https://github.com/coreos/kube-aws/pull/195) for that. With his work, you could provide cfn params via terraform to specify which vpc, subnet, nat gateway, etc to be used to deploy an kube-aws cluster into an exsiting vpc managed by terraform. I'd appreciate it if you could confirm that all the values you care about are addressed or missed in the pr.

this is already available in kube-aws as of today.

**Comment by johanneswuerbach** [comment]
Thanks for the update @mumoshu we started using https://github.com/kubernetes/kops, which has also experimental CoreOS support now and are quite happy with that.

**Comment by mumoshu** [comment]
@johanneswuerbach Thanks for the info!
I'm very interested; are you customizing terraform templates generated by kops, or just using kops commands to manage your clusters?

**Comment by johanneswuerbach** [comment]
We are managing various other parts of our infrastructure already using terraform and mainly using the kops output to extend the clusters with some shared modules like instance monitoring, vpc peering, etc. The clusters themselves are mostly managed using kops.

**Comment by mumoshu** [comment]
Thanks for the info!
Great 👍 Good to know kops could support such use cases.

**Comment by icereval** [comment]
Also @mgoodness has put up a CoreOS/Terraform/AWS project that is very friendly, might be worth having a look at.

https://github.com/mgoodness/kubit

**Comment by jengo** [comment]
I would rather use Terraform over CloudFormation any day.  Terraform fixes a lot of the problems that CF has.  For example, there are rare situations with CF that updates to a stack can fail and you have no way to correct them.  Like when someone makes a console change that conflicts with what CF is trying to do. 

TF has many advantages over CF.  Far cleaner syntax, ability to continue during a failure instead of going back to the beginning.  Ability to import existing resources.  You can also use terraform plan as a means of auditing infrastructure for expected vs actual state.

I do understand that CF is standard with AWS and you don't want to create dependancies for 3rd party tools.  But, personally, I think it's worth it. CF is very dated and AWS isn't giving it much love.

**Comment by c-knowles** [comment]
I saw that the [tectonic-installer](https://github.com/coreos/tectonic-installer) also seems to use some terraform.

**Comment by redbaron** [comment]
@jengo lets not discuss TF vs CF as there can be very polar opinions on this subject which don't change the fact that *every single non-templated line* here https://github.com/kubernetes-incubator/kube-aws/blob/a984fd92280430424236cc2d40f0b4ff1b926e40/core/controlplane/config/templates/stack-template.json needs to be represented in a code just to have ability to produce a stack in TF format in addition to CF format. Any volunteers? :)

Alternative approach would be t write/find CF to TF converter, when fully rendered CF stack is post-processed into TF files.I am not aware of such project myself though :(

**Comment by mumoshu** [comment]
Just my two cents.

I do use Terraform for managing a whole or a fundamental part of my infrastructure. More concretely, I use TF for managing existing, long-living, production AWS resources which shouldn't be removed without a super careful review. On the other hand, I use CloudFormation for managing an occasionally recreated, disposable set of AWS resources. I'd rather create 1 TF env for my whole infrastructure and at most 2 CF stacks for kube-aws clusters managed in the TF env.

Terraform can be used for both but CF is just better when it comes to e.g. rolling update of EC2 instances under an ASG without down time(utilizing wait signals). I believe you would know that even Terraform supports `cloudformation_stack` resource for the aws provider for that. Terraform isn't always interchangeable with CF. That's why I'd rather use TF AND CF.

Also, IMHO, using a CF stack is a disposable AWS resource is completely OK. You may know that creating an EC2 instance can't be terminated by any chance isn't a good idea? The same applies (for m) to a CloudFormation stack.

For example, managing e.g. internet-facing ELBs serving your customers with a  CloudFormation stack isn't a good idea for me. I'd use Terraform for that. On the other hand, a kube-aws cluster is considered disposable (for now) like an EC2 instance. I've been even recommending to have 2 kube-aws clusters temporarily for upgrading kube-aws without down time by migrating your deployments, pods, daemonsets to the new one gradually. It would look like what you do when migrating EC2 instances.

Btw I DO wish if we had a custom Terraform resource for the aws provider named `kube_aws_cluster` which is used to manage one or more kube-aws clusters with Terraform 😃 so that every modification on my infrastructure including kube-aws clusters can be managed via Terraform, while still utilizing the power of CF like wait signals and nested stacks, cross-stack references, etc.

**Comment by eedgar** [comment]
We are looking at aws china and that area does not have route53 nor kms.  So we need to integrate with 3rd party services like powerdns and/or hashicorp vault for similar functionality.  Supporting terraform based templates would allow us to use kube-aws in china.  Being purely cloudformation strictly ties us to ALL aws resources.
