### ISSUE TITLE
[0.14.3 => 0.15] Regression regarding Persistent Volume

### ISSUE THREAD

**Issue by sei-nicolas** [kubernetes-incubator/kube-aws#1829]
Using the same original cluster.yaml file:
- With release 0.14.3, it's possible to use an Amazon EBS volume as a persistent volume, then declare a persitent volume claim to mount inside a deploy
- With release 0.15, the pod creation fails with the error "Failed to get AWS Cloud Provider. GetCloudProvider returned <nil> instead"

I saw that this message could happen if kubelet is not started with the parameter "--cloud-provider=aws" but manually adding it (api/node) does not change anything.

**Comment by davidmccormick** [comment]
Apologies, yes I hadn't realised that the PVS were no longer working with the `cloud-controller-manager`.

A fix is to add the `kube-controller-manager` flag `--cloud-provider=aws` which restores PVC functionality (but throws a deprecation warning on k8s 1.16).

I think the right solution will be to make `cloud-controller-manager` an experimental feature and also add in CSI ebs volume support so that they can be used together (which I believe is the intended path forward as the aws cloud provider is gradually removed from core k8s).

I'll look at a patch which we can release as v0.15.1 containing these fixes.

**Comment by dominicgunn** [comment]
This issue was resolved with https://github.com/kubernetes-incubator/kube-aws/pull/1832.
