### ISSUE TITLE
Allow flannel to use a different backend

### ISSUE THREAD

**Issue by ArchiFleKs** [kubernetes-incubator/kube-aws#241]
Hi, by default flannel uses VXLAN to encapsulated traffic which is fine on AWS, because MTU are big but it can diminish performance compare to native L3 because of encapsulation.

[Flannel](https://github.com/coreos/flannel) has multiple backends like `aws-vpc` which can enable native vpc route table and optimize network performance.

I'm not saying we should make it default, but maybe offer the choice.

Currently VPC route table are limited to 50 entries so it would be relatively small cluster. But it something to consider.

**Comment by mumoshu** [comment]
Thanks for raising this @ArchiFleKs!
I'd rather like to add a feature to allow switching among backends as long as it is documented carefully with the limitation. IMHO that backend is just for experiments for me with the limitation but I'd like to hear from the community for real-world use-cases.

**Comment by redbaron** [comment]
@mumoshu , @caseydavenport pointed me to a nice descriptive doc regarding calico + flannel: https://github.com/projectcalico/canal/blob/49fe5a519d4d2b1e02a38e9f8667416367f8c702/README.md which lists AWS VPC backend as "not recommended".

**Comment by Overbryd** [comment]
Here is a great article comparing the `host-gw`, `vxlan` and `aws-vpc` networking backends performance wise. http://machinezone.github.io/research/networking-solutions-for-kubernetes/

`host-gw` seems to be a winning choice, but source/destination checks for these ec2 instances must be disabled for this to work.

I would appreciate switching flannel backends. Especially since the default options has the worst performance.

**Comment by irlevesque** [comment]
Has there been any further consideration of this request? Our testing shows that the vxlan performance hit is too substantial for our production cluster. Would love to see more flexible CNI configuration options.
