### ISSUE TITLE
Identify missing features to support  continuous cluster management

### ISSUE THREAD

**Issue by redbaron** [kubernetes-incubator/kube-aws#311]
as per @mumoshu , kube-aws doesn't support continuous cluster management , whole cluster need to be recreated between kube-aws version and use-case of just applying updates to an existing cluster is neither supported nor tested.

If there is interests in supporting continuous cluster management, then lets identify what is missing to make it happen.

**Comment by mumoshu** [comment]
Thanks for raising this issue!
AFAICS:

* Applying "updates" to a cluster is supported as much as supported by cloudformation.
  * Specifically, rolling-updates to worker nodes and controller nodes (1) to change instance type and/or volumes, (2) to toggle experimental features like nodeDrainer, waitSignal, awsNodeLabels, nodeLabels, awsEnvironment should already be supported today
* Applying "upgrades" i.e. running `kube-aws update` against a cluster created with an older version of kube-aws may or may not work. As of today, `kube-aws update` won't work if kube-aws made a big structural change its stack templates between kube-aws versions. An example is the recenct transition from statically assigned ips to dynamically assigned ips for etcd nodes.

**Comment by c-knowles** [comment]
It won't apply to every use case but I tend to run an export of all the k8s definitions, import them to the new cluster and then switch the DNS over (each k8s stack is versioned). That method is not really possible on the more stateful cases but works quite well for most of our stateless applications.

**Comment by danielfm** [comment]
One thing that's bothering me is how we are versioning new releases; just by looking at the version numbers, we should be able to tell if one release is compatible with another.

[Tagging a release properly](http://semver.org) is the first step towards more stable software. For instance, take v0.9.3 and the current RC of 0.9.4. These are _completely_ different releases, with drastic changes in UX. Why not tag the next release as `v1.0.0`, which makes completely clear that this would be a _major_ release that possibly breaks something (different internal design, UX, configuration files, etc)?

So, in my opinion, it's about time we release a non-rc version to serve as the basis for next releases, and start tagging them properly according to what changed.

The other thing that bothers me a little is the amount of changes between versions. I think we should release more frequently, taking an extra care to break up big PRs into smaller (hopefully backwards compatible) changes. This makes it easier for us - the users - to reason about what changed between releases and how to upgrade.

**Comment by c-knowles** [comment]
I think especially if coreos are not signing these any more, it'd be better to release v1 and less RCs. There's still a few things on the roadmap that main maintainer @mumoshu may wish to have prior to v1.

Just to play devil's advocate for a second, semver allows completely breaking changes on 0.x releases.

**Comment by mumoshu** [comment]
@danielfm Thanks for your feedbacks!

> One thing that's bothering me is how we are versioning new releases; just by looking at the version numbers, we should be able to tell if one release is compatible with another.

I'm sorry to say but not really.

Though kube-aws is even production-ready in IMHO(I'm already running our own k8s cluster serving serious production-workload at our company since I became the maintainer of kube-aws), it doesn't mean kube-aws is feature-complete or even design-complete, hence it is versioned v0.9.x.

We're still developing kube-aws aggressively to support various use-cases and features, improvements listed in our [roadmap](https://github.com/coreos/kube-aws/blob/master/ROADMAP.md)(btw it is free to be pull-requested 😄), which would drastically IMPROVE how we deploy k8s on AWS. Not all of the items can be achieved in backward-compatible ways in various aspects(stack template template, resulting stack template, cluster.yaml, resulting AWS resources and their relationships).

BTW/FYI that's why I tend to recommend users to upgrade kube-aws versions by creating and switching to a newly created cluster like @c-knowles said in https://github.com/coreos/kube-aws/issues/311#issuecomment-278833172

No useful features would be dropped but deprecated syntaxes and features would certainly dropped in the process of improvements.

For example, a recent change #315 would definitely affect you by forcing you to rewrite your `cluster.yaml` a bit to migrate to new configuration keys and syntaxes and tweak your own `stack-template.json` customization script if any. However no feature is dropped from kube-aws.

Also let me clarify that for example #315 changed how node pools are created drastically but node pools had been a experimental feature since v0.9.1, in the first place. I changed it according to our roadmap and the fact it was an experimental feature.
I guess we never changed U/X regarding non-experimental features drastically, right?

However, it may or may not be your actual concern or issue.

Could you just share us your feelings once again after reading my explanations above?

* Would the current numbers and degrees of NECESSARY changes makes you feel painful?
* Does just releasing frequently fundamentally resolve your potential issue?
* Could recent drastic changes be managed in backward-compatible ways? (Contribution welcomed 👍)
* Would an migration guide between kube-aws non-rc versions would help? (Contribution welcomed 👍)

**Comment by danielfm** [comment]
@mumoshu I use kube-aws since its early days and I'm very thankful for all the effort and love you and everyone else put into this project, so I'm sorry if my comments sounded too harsh or disrespectful in any way. That was not my intention. ❤️ 

> Though kube-aws is even production-ready in IMHO(I'm already running our own k8s cluster serving serious production-workload at our company since I became the maintainer of kube-aws), it doesn't mean kube-aws is feature-complete or even design-complete, hence it is versioned v0.9.x.

I particularly don't believe there's such a thing as a feature-complete software, and in that sense, there's no version that's more special than the other. Version 1.0 is a nice milestone, yes, but it by no means represent a feature-complete software; take [Kubernetes itself](https://github.com/kubernetes/kubernetes/releases/tag/v1.0.0) as an example.

> We're still developing kube-aws aggressively to support various use-cases and features, improvements listed in our roadmap(btw it is free to be pull-requested 😄), which would drastically IMPROVE how we deploy k8s on AWS. Not all of the items can be achieved in backward-compatible ways in various aspects(stack template template, resulting stack template, cluster.yaml, resulting AWS resources and their relationships).

Yes, and that's perfectly fine! What I said is that it would probably be better if we properly tag each release in order to make it more clear whether it breaks something, or demands re-generation of some cluster asset files, or something like that.

> BTW/FYI that's why I tend to recommend users to upgrade kube-aws versions by creating and switching to a newly created cluster

That's exactly what I've been doing here as well. 👍 

> For example, a recent change #315 would definitely affect you by forcing you to rewrite your cluster.yaml a bit to migrate to new configuration keys and syntaxes and tweak your own `stack-template.json` customization script if any. However no feature is dropped from kube-aws.
>
> Also let me clarify that for example #315 changed how node pools are created drastically but node pools had been a experimental feature since v0.9.1, in the first place. I changed it according to our roadmap and the fact it was an experimental feature.

I also like the idea of having experimental features. Once an experimental feature "graduates", however, it might break something or require changes to the cluster operation workflow, introduce new commands, etc, so what I said was to track these changes down and tag the releases accordingly.

> I guess we never changed U/X regarding non-experimental features drastically, right?

I think so. 👍

---

Now answering your questions:

> Would the current numbers and degrees of NECESSARY changes makes you feel painful?

I'm not sure I understand the question.

> Does just releasing frequently fundamentally resolve your potential issue?

Not fundamentally, no, but it certainly makes things easier when deciding which upgrades I'd want to incorporate to my setup at any given cluster upgrade I choose to make.

If we follow semver here, it would be easier to see which new features I'm prepared to use in my new cluster. This is just an example of what I mean:

- Patch-level releases (ex: 1.1.1 -> 1.1.2) should be safe to apply without the need to re-render any cluster assets or recreate the entire cluster, so it's basically one `kube-aws update` away
- Minor-level releases (ex: 1.1.2 -> 1.2.0) might require re-render of some cluster asset files but should be safe to apply without recreating the entire cluster
- Major-level releases (ex: 1.2.0 -> 2.0.0) are not safe to apply to a running cluster, so the right way to do it is to upgrade via replacement

> Could recent drastic changes be managed in backward-compatible ways?

Probably not, but, again, having multiple backward-incompatible changes in one release does not help either.

> Would an migration guide between kube-aws non-rc versions would help?

Definitely yes!

**Comment by mumoshu** [comment]
@danielfm 

> Probably not, but, again, having multiple backward-incompatible changes in one release does not help either.

Certainly. I'll, at least, try to limit the number of backward-incompatible changes to just 1 👍 
Btw, in the upcoming v0.9.5, it will be etcd; H/A etcd drastically changes how etcd nodes are managed and etcd endpoints are determined/shared. I could'nt figure out how I could make it in a backward-compatible way...
