### ISSUE TITLE
v0.9.4: How to launch my first cluster with worker node pools?

### ISSUE THREAD

**Issue by qpaulson** [kubernetes-incubator/kube-aws#378]
Currently it seems that it is impossible to use kube-aws to initialize a cluster in the ca-central-1 region.

The controllers do not start correctly and the cluster does not come up.

I did some digging and could not find any insights into this.

**Comment by gianrubio** [comment]
@qpaulson could you share your cloudformation logs?

**Comment by qpaulson** [comment]
I've gotten further now.. Initially the controller would not startup.. I've given it a bigger instance type on aws and it seems to be starting now.. 

Currently 
- The cloudformation stack completes successfully. 
- The DNS Zone is not updated ( I updated it manually )
- kubectl get nodes shows only the controller
`NAME                                          STATUS    AGE
ip-10-0-0-251.ca-central-1.compute.internal   Ready     4h
`
- I've confirmed that kubelet and docker are running on the worker nodes.
- I've confirmed etcd is up and running on the etcd nodes
- I've confirmed there are connections from all the servers in the cluster to the etcd node
`etcd2   1639 etcd    9u     IPv4              24906      0t0    TCP ip-10-0-0-17.ca-central-1.compute.internal:etcd-server->ip-10-0-0-245.ca-central-1.compute.internal:54498 (ESTABLISHED)
etcd2   1639 etcd   10u     IPv4              22396      0t0    TCP ip-10-0-0-17.ca-central-1.compute.internal:57636->ip-10-0-0-82.ca-central-1.compute.internal:etcd-server (ESTABLISHED)
etcd2   1639 etcd   11u     IPv4              22398      0t0    TCP ip-10-0-0-17.ca-central-1.compute.internal:57638->ip-10-0-0-82.ca-central-1.compute.internal:etcd-server (ESTABLISHED)
etcd2   1639 etcd   12u     IPv4              22399      0t0    TCP ip-10-0-0-17.ca-central-1.compute.internal:etcd-server->ip-10-0-0-82.ca-central-1.compute.internal:42200 (ESTABLISHED)
etcd2   1639 etcd   13u     IPv4              22400      0t0    TCP ip-10-0-0-17.ca-central-1.compute.internal:etcd-server->ip-10-0-0-82.ca-central-1.compute.internal:42198 (ESTABLISHED)
etcd2   1639 etcd   14u     IPv4              24829      0t0    TCP ip-10-0-0-17.ca-central-1.compute.internal:57656->ip-10-0-0-82.ca-central-1.compute.internal:etcd-server (ESTABLISHED)
etcd2   1639 etcd   15u     IPv4              25634      0t0    TCP ip-10-0-0-17.ca-central-1.compute.internal:etcd-client->ip-10-0-0-65.ca-central-1.compute.internal:51152 (ESTABLISHED)
etcd2   1639 etcd   16u     IPv4              22502      0t0    TCP ip-10-0-0-17.ca-central-1.compute.internal:40642->ip-10-0-0-245.ca-central-1.compute.internal:etcd-server (ESTABLISHED)
etcd2   1639 etcd   17u     IPv4              24895      0t0    TCP ip-10-0-0-17.ca-central-1.compute.internal:40644->ip-10-0-0-245.ca-central-1.compute.internal:etcd-server (ESTABLISHED)
etcd2   1639 etcd   18u     IPv4              24896      0t0    TCP ip-10-0-0-17.ca-central-1.compute.internal:etcd-server->ip-10-0-0-245.ca-central-1.compute.internal:54490 (ESTABLISHED)
etcd2   1639 etcd   19u     IPv4              24898      0t0    TCP ip-10-0-0-17.ca-central-1.compute.internal:etcd-server->ip-10-0-0-245.ca-central-1.compute.internal:54492 (ESTABLISHED)
etcd2   1639 etcd   20u     IPv4              22503      0t0    TCP ip-10-0-0-17.ca-central-1.compute.internal:40646->ip-10-0-0-245.ca-central-1.compute.internal:etcd-server (ESTABLISHED)
etcd2   1639 etcd   21u     IPv4              22505      0t0    TCP ip-10-0-0-17.ca-central-1.compute.internal:57864->ip-10-0-0-82.ca-central-1.compute.internal:etcd-server (ESTABLISHED)
etcd2   1639 etcd   22u     IPv4              24901      0t0    TCP ip-10-0-0-17.ca-central-1.compute.internal:etcd-server->ip-10-0-0-82.ca-central-1.compute.internal:42344 (ESTABLISHED)
etcd2   1639 etcd   23u     IPv4              24904      0t0    TCP ip-10-0-0-17.ca-central-1.compute.internal:40650->ip-10-0-0-245.ca-central-1.compute.internal:etcd-server (ESTABLISHED)
etcd2   1639 etcd   24u     IPv4              25641      0t0    TCP ip-10-0-0-17.ca-central-1.compute.internal:etcd-client->ip-10-0-0-251.ca-central-1.compute.internal:49398 (ESTABLISHED)
`
- I've checked the security groups, there should be no connectivity problems between the controller and the worker nodes.

**Comment by qpaulson** [comment]
Here are some logs form the controller 

==> kube-apiserver-ip-10-0-0-251.ca-central-1.compute.internal_kube-system_kube-apiserver-6c30764eec42e66cd9b3891ce76e5f28a34d3e86b4caa45617dcad746b868e35.log <==
{"log":"I0305 00:49:42.671589       1 logs.go:41] http: TLS handshake error from 10.0.0.230:3060: EOF\n","stream":"stderr","time":"2017-03-05T00:49:42.671739704Z"}
{"log":"I0305 00:49:43.051922       1 logs.go:41] http: TLS handshake error from 10.0.0.75:1860: EOF\n","stream":"stderr","time":"2017-03-05T00:49:43.05220962Z"}

==> kube-scheduler-ip-10-0-0-251.ca-central-1.compute.internal_kube-system_kube-scheduler-7159a66613ad5f639649bbb4ed385b0ea34fd3fe8ec6ab7aa6abf428caa4f03d.log <==
{"log":"E0305 00:49:43.724337       1 factory.go:583] Error scheduling kube-system kube-dns-autoscaler-2813114833-89qw8: pod (kube-dns-autoscaler-2813114833-89qw8) failed to fit in any node\n","stream":"stderr","time":"2017-03-05T00:49:43.724693425Z"}
{"log":"fit failure summary on nodes : PodToleratesNodeTaints (1); retrying\n","stream":"stderr","time":"2017-03-05T00:49:43.724724026Z"}
{"log":"I0305 00:49:43.724475       1 event.go:217] Event(api.ObjectReference{Kind:\"Pod\", Namespace:\"kube-system\", Name:\"kube-dns-autoscaler-2813114833-89qw8\", UID:\"34f5a65f-0117-11e7-9f11-02bae12ab48b\", APIVersion:\"v1\", ResourceVersion:\"125\", FieldPath:\"\"}): type: 'Warning' reason: 'FailedScheduling' pod (kube-dns-autoscaler-2813114833-89qw8) failed to fit in any node\n","stream":"stderr","time":"2017-03-05T00:49:43.724730711Z"}
{"log":"fit failure summary on nodes : PodToleratesNodeTaints (1)\n","stream":"stderr","time":"2017-03-05T00:49:43.724736544Z"}
{"log":"E0305 00:49:43.724578       1 factory.go:583] Error scheduling kube-system kubernetes-dashboard-v1.5.1-lm737: pod (kubernetes-dashboard-v1.5.1-lm737) failed to fit in any node\n","stream":"stderr","time":"2017-03-05T00:49:43.724740261Z"}
{"log":"fit failure summary on nodes : PodToleratesNodeTaints (1); retrying\n","stream":"stderr","time":"2017-03-05T00:49:43.724743866Z"}
{"log":"I0305 00:49:43.724636       1 event.go:217] Event(api.ObjectReference{Kind:\"Pod\", Namespace:\"kube-system\", Name:\"kubernetes-dashboard-v1.5.1-lm737\", UID:\"34f3d2ca-0117-11e7-9f11-02bae12ab48b\", APIVersion:\"v1\", ResourceVersion:\"101\", FieldPath:\"\"}): type: 'Warning' reason: 'FailedScheduling' pod (kubernetes-dashboard-v1.5.1-lm737) failed to fit in any node\n","stream":"stderr","time":"2017-03-05T00:49:43.724747401Z"}
{"log":"fit failure summary on nodes : PodToleratesNodeTaints (1)\n","stream":"stderr","time":"2017-03-05T00:49:43.724752001Z"}
{"log":"E0305 00:49:43.725915       1 factory.go:583] Error scheduling kube-system heapster-v1.2.0-3646253287-lwhn6: pod (heapster-v1.2.0-3646253287-lwhn6) failed to fit in any node\n","stream":"stderr","time":"2017-03-05T00:49:43.726498436Z"}
{"log":"fit failure summary on nodes : PodToleratesNodeTaints (1); retrying\n","stream":"stderr","time":"2017-03-05T00:49:43.72651273Z"}
{"log":"I0305 00:49:43.725953       1 event.go:217] Event(api.ObjectReference{Kind:\"Pod\", Namespace:\"kube-system\", Name:\"heapster-v1.2.0-3646253287-lwhn6\", UID:\"34f5913e-0117-11e7-9f11-02bae12ab48b\", APIVersion:\"v1\", ResourceVersion:\"121\", FieldPath:\"\"}): type: 'Warning' reason: 'FailedScheduling' pod (heapster-v1.2.0-3646253287-lwhn6) failed to fit in any node\n","stream":"stderr","time":"2017-03-05T00:49:43.726517307Z"}
{"log":"fit failure summary on nodes : PodToleratesNodeTaints (1)\n","stream":"stderr","time":"2017-03-05T00:49:43.726522598Z"}
{"log":"E0305 00:49:43.727256       1 factory.go:583] Error scheduling kube-system calico-policy-controller-4200321479-zjsg6: pod (calico-policy-controller-4200321479-zjsg6) failed to fit in any node\n","stream":"stderr","time":"2017-03-05T00:49:43.727529304Z"}
{"log":"fit failure summary on nodes : PodToleratesNodeTaints (1); retrying\n","stream":"stderr","time":"2017-03-05T00:49:43.727540652Z"}
{"log":"I0305 00:49:43.727329       1 event.go:217] Event(api.ObjectReference{Kind:\"Pod\", Namespace:\"kube-system\", Name:\"calico-policy-controller-4200321479-zjsg6\", UID:\"34f54f27-0117-11e7-9f11-02bae12ab48b\", APIVersion:\"v1\", ResourceVersion:\"114\", FieldPath:\"\"}): type: 'Warning' reason: 'FailedScheduling' pod (calico-policy-controller-4200321479-zjsg6) failed to fit in any node\n","stream":"stderr","time":"2017-03-05T00:49:43.727544507Z"}
{"log":"fit failure summary on nodes : PodToleratesNodeTaints (1)\n","stream":"stderr","time":"2017-03-05T00:49:43.727561126Z"}
{"log":"E0305 00:49:44.736412       1 factory.go:583] Error scheduling kube-system kube-dns-782804071-v15ws: pod (kube-dns-782804071-v15ws) failed to fit in any node\n","stream":"stderr","time":"2017-03-05T00:49:44.736649907Z"}
{"log":"fit failure summary on nodes : PodToleratesNodeTaints (1); retrying\n","stream":"stderr","time":"2017-03-05T00:49:44.736679595Z"}
{"log":"I0305 00:49:44.736714       1 event.go:217] Event(api.ObjectReference{Kind:\"Pod\", Namespace:\"kube-system\", Name:\"kube-dns-782804071-v15ws\", UID:\"358097e0-0117-11e7-9f11-02bae12ab48b\", APIVersion:\"v1\", ResourceVersion:\"140\", FieldPath:\"\"}): type: 'Warning' reason: 'FailedScheduling' pod (kube-dns-782804071-v15ws) failed to fit in any node\n","stream":"stderr","time":"2017-03-05T00:49:44.736973638Z"}
{"log":"fit failure summary on nodes : PodToleratesNodeTaints (1)\n","stream":"stderr","time":"2017-03-05T00:49:44.736988388Z"}

**Comment by mumoshu** [comment]
Thanks for trying kube-aws!
Would you mind sharing us your cluster.yaml?
Perhaps you're missing `createRecordSet: true` and the `nodePools:` array
in it?

2017年3月5日(日) 13:04 qpaulson <notifications@github.com>:

**Comment by qpaulson** [comment]
@mumoshu, @gianrubio 

 I just tried re-creating my cluster with more powerful nodes for the controller and workers. I set them both to m4.4xlarge didn't have any effect. 

@mumoshu , you are correct in both of your guesses. I was missing createRecordSet: true.  That explains my lack of DNS :) 

I've never used nodePools before though, so that one is new to me.. I am reading up on it now.. 

Just for review, Here is my cluster.yaml:

**cluster.yaml:**
clusterName: qkube1
externalDNSName: qkube1.aws.central1.com
hostedZone: "aws.central1.com"
hostedZoneId: "Z2LGBQ7H2AU015"
keyName: aws-qpaulson-ca-central-1
region: ca-central-1
availabilityZone: ca-central-1a
kmsKeyArn: "arn:aws:kms:ca-central-1:368897584504:key/a7f8fb40-fc60-4c06-8a5a-61030dfb9994"
controller:
  autoScalingGroup:
    minSize: 1
    maxSize: 3
controllerInstanceType: m4.4xlarge
worker:
  autoScalingGroup:
    minSize: 2
    maxSize: 5
    rollingUpdateMinInstancesInService: 2
workerInstanceType: m4.4xlarge
workerRootVolumeSize: 100
workerSecurityGroupIds:
etcdCount: 3
etcdInstanceType: t2.xlarge
useCalico: true
containerRuntime: docker
stackTags:
  Name: "qkube1"
  Environment: "qa"
  c1:cost-centre: "4401"
  c1:created-by: "Q"

**Comment by mumoshu** [comment]
Hi!
Please use kube-aws 0.9.4 and `worker.nodePools` in cluster.yaml to add
worker nodes to your cluster.

2017年3月5日(日) 15:01 qpaulson <notifications@github.com>:

Here are some logs form the controller

==>
kube-apiserver-ip-10-0-0-251.ca-central-1.compute.internal_kube-system_kube-apiserver-6c30764eec42e66cd9b3891ce76e5f28a34d3e86b4caa45617dcad746b868e35.log
<==
{"log":"I0305 00:49:42.671589 1 logs.go:41] http: TLS handshake error from
10.0.0.230:3060:
EOF\n","stream":"stderr","time":"2017-03-05T00:49:42.671739704Z"}
{"log":"I0305 00:49:43.051922 1 logs.go:41] http: TLS handshake error from
10.0.0.75:1860:
EOF\n","stream":"stderr","time":"2017-03-05T00:49:43.05220962Z"}

==>
kube-scheduler-ip-10-0-0-251.ca-central-1.compute.internal_kube-system_kube-scheduler-7159a66613ad5f639649bbb4ed385b0ea34fd3fe8ec6ab7aa6abf428caa4f03d.log
<==
{"log":"E0305 00:49:43.724337 1 factory.go:583] Error scheduling
kube-system kube-dns-autoscaler-2813114833-89qw8: pod
(kube-dns-autoscaler-2813114833-89qw8) failed to fit in any
node\n","stream":"stderr","time":"2017-03-05T00:49:43.724693425Z"}
{"log":"fit failure summary on nodes : PodToleratesNodeTaints (1);
retrying\n","stream":"stderr","time":"2017-03-05T00:49:43.724724026Z"}
{"log":"I0305 00:49:43.724475 1 event.go:217]
Event(api.ObjectReference{Kind:"Pod", Namespace:"kube-system",
Name:"kube-dns-autoscaler-2813114833-89qw8",
UID:"34f5a65f-0117-11e7-9f11-02bae12ab48b", APIVersion:"v1",
ResourceVersion:"125", FieldPath:""}): type: 'Warning' reason:
'FailedScheduling' pod (kube-dns-autoscaler-2813114833-89qw8) failed to fit
in any node\n","stream":"stderr","time":"2017-03-05T00:49:43.724730711Z"}
{"log":"fit failure summary on nodes : PodToleratesNodeTaints
(1)\n","stream":"stderr","time":"2017-03-05T00:49:43.724736544Z"}
{"log":"E0305 00:49:43.724578 1 factory.go:583] Error scheduling
kube-system kubernetes-dashboard-v1.5.1-lm737: pod
(kubernetes-dashboard-v1.5.1-lm737) failed to fit in any
node\n","stream":"stderr","time":"2017-03-05T00:49:43.724740261Z"}
{"log":"fit failure summary on nodes : PodToleratesNodeTaints (1);
retrying\n","stream":"stderr","time":"2017-03-05T00:49:43.724743866Z"}
{"log":"I0305 00:49:43.724636 1 event.go:217]
Event(api.ObjectReference{Kind:"Pod", Namespace:"kube-system",
Name:"kubernetes-dashboard-v1.5.1-lm737",
UID:"34f3d2ca-0117-11e7-9f11-02bae12ab48b", APIVersion:"v1",
ResourceVersion:"101", FieldPath:""}): type: 'Warning' reason:
'FailedScheduling' pod (kubernetes-dashboard-v1.5.1-lm737) failed to fit in
any node\n","stream":"stderr","time":"2017-03-05T00:49:43.724747401Z"}
{"log":"fit failure summary on nodes : PodToleratesNodeTaints
(1)\n","stream":"stderr","time":"2017-03-05T00:49:43.724752001Z"}
{"log":"E0305 00:49:43.725915 1 factory.go:583] Error scheduling
kube-system heapster-v1.2.0-3646253287-lwhn6: pod
(heapster-v1.2.0-3646253287-lwhn6) failed to fit in any
node\n","stream":"stderr","time":"2017-03-05T00:49:43.726498436Z"}
{"log":"fit failure summary on nodes : PodToleratesNodeTaints (1);
retrying\n","stream":"stderr","time":"2017-03-05T00:49:43.72651273Z"}
{"log":"I0305 00:49:43.725953 1 event.go:217]
Event(api.ObjectReference{Kind:"Pod", Namespace:"kube-system",
Name:"heapster-v1.2.0-3646253287-lwhn6",
UID:"34f5913e-0117-11e7-9f11-02bae12ab48b", APIVersion:"v1",
ResourceVersion:"121", FieldPath:""}): type: 'Warning' reason:
'FailedScheduling' pod (heapster-v1.2.0-3646253287-lwhn6) failed to fit in
any node\n","stream":"stderr","time":"2017-03-05T00:49:43.726517307Z"}
{"log":"fit failure summary on nodes : PodToleratesNodeTaints
(1)\n","stream":"stderr","time":"2017-03-05T00:49:43.726522598Z"}
{"log":"E0305 00:49:43.727256 1 factory.go:583] Error scheduling
kube-system calico-policy-controller-4200321479-zjsg6: pod
(calico-policy-controller-4200321479-zjsg6) failed to fit in any
node\n","stream":"stderr","time":"2017-03-05T00:49:43.727529304Z"}
{"log":"fit failure summary on nodes : PodToleratesNodeTaints (1);
retrying\n","stream":"stderr","time":"2017-03-05T00:49:43.727540652Z"}
{"log":"I0305 00:49:43.727329 1 event.go:217]
Event(api.ObjectReference{Kind:"Pod", Namespace:"kube-system",
Name:"calico-policy-controller-4200321479-zjsg6",
UID:"34f54f27-0117-11e7-9f11-02bae12ab48b", APIVersion:"v1",
ResourceVersion:"114", FieldPath:""}): type: 'Warning' reason:
'FailedScheduling' pod (calico-policy-controller-4200321479-zjsg6) failed
to fit in any
node\n","stream":"stderr","time":"2017-03-05T00:49:43.727544507Z"}
{"log":"fit failure summary on nodes : PodToleratesNodeTaints
(1)\n","stream":"stderr","time":"2017-03-05T00:49:43.727561126Z"}
{"log":"E0305 00:49:44.736412 1 factory.go:583] Error scheduling
kube-system kube-dns-782804071-v15ws: pod (kube-dns-782804071-v15ws) failed
to fit in any
node\n","stream":"stderr","time":"2017-03-05T00:49:44.736649907Z"}
{"log":"fit failure summary on nodes : PodToleratesNodeTaints (1);
retrying\n","stream":"stderr","time":"2017-03-05T00:49:44.736679595Z"}
{"log":"I0305 00:49:44.736714 1 event.go:217]
Event(api.ObjectReference{Kind:"Pod", Namespace:"kube-system",
Name:"kube-dns-782804071-v15ws",
UID:"358097e0-0117-11e7-9f11-02bae12ab48b", APIVersion:"v1",
ResourceVersion:"140", FieldPath:""}): type: 'Warning' reason:
'FailedScheduling' pod (kube-dns-782804071-v15ws) failed to fit in any
node\n","stream":"stderr","time":"2017-03-05T00:49:44.736973638Z"}
{"log":"fit failure summary on nodes : PodToleratesNodeTaints
(1)\n","stream":"stderr","time":"2017-03-05T00:49:44.736988388Z"}

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/coreos/kube-aws/issues/378#issuecomment-284196423>, or mute
the thread

**Comment by qpaulson** [comment]
@mumoshu I gave this a try, but i'm having an issue.

Error: Failed to initialize cluster driver: file cluster.yaml: invalid node pool at index 0: public subnets required by default for node pool missing in cluster.yaml.
define one or more public subnets in cluster.yaml or explicitly reference private subnets from node pool by specifying nodePools[].subnets[].name

I don't plan to have any of my nodes within a public subnet. I plan to put ELB's in the Public Subnets.


I've setup this:

subnets:
   - name: PrivateSubnet1
     availabilityZone: ca-central-1a
     id: "subnet-857286ec"
   - name: PrivateSubnet2
     availabilityZone: ca-central-1b
     id: "subnet-2434205c"



worker:
  nodePools:
      name: nodepool1
      subnet:
        name: PrivateSubnet1
      autoScalingGroup:
        minSize: 1
        maxSize: 5
        rollingUpdateMinInstancesInService: 2
    - # Name of the second pool
      name: nodepool2
      subnet:
        name: PrivateSubnet2
      autoScalingGroup:
        minSize: 1
        maxSize: 5
        rollingUpdateMinInstancesInService: 2

**Comment by mumoshu** [comment]
Thanks for taking your time!
Please try `worker.nodePools[].subnets[].name` instead of the singular `
subenet.name`.
2017年3月5日(日) 17:35 qpaulson <notifications@github.com>:

**Comment by qpaulson** [comment]
@mumoshu That makes more sense.. :) 

I think theres something wrong with the yaml now.. I've checked for tabs and stuff, but its still not wokring:

../kube-aws validate --s3-uri=s3://kubernetes-state-backend/qkube1
Error: Failed to initialize cluster driver: file cluster.yaml: failed to parse config: yaml: unmarshal errors:
  line 124: cannot unmarshal !!map into []model.Subnet
  line 132: cannot unmarshal !!map into []model.Subnet


subnets:
  - name: PrivateSubnet1
    availabilityZone: ca-central-1a
    id: "subnet-857286ec"
    public: true
  - name: PrivateSubnet2
    availabilityZone: ca-central-1b
    id: "subnet-2434205c"
    public: true



worker:
  nodePools:
    - name: nodepool1
      subnets:
        name: PrivateSubnet1
      autoScalingGroup:
        minSize: 1
        maxSize: 5
        rollingUpdateMinInstancesInService: 2
    - name: nodepool2
      subnets:
        name: PrivateSubnet2
      autoScalingGroup:
        minSize: 1
        maxSize: 5
        rollingUpdateMinInstancesInService: 2

**Comment by mumoshu** [comment]
Hi @qpaulson!
JFYI please try to surround your code with ` ``` ` so that your yaml snippet would look nicer :smile:
I've updated your comment accordingly.

The error says that you've coded `subnets` as a yaml map but it must be an array.
Instead of:
```yaml
- name: nodepool1
  subnets:
    name: PrivateSubnet1
```
It must be defined like:
```yaml
- name: nodepool1
  subnets:
  - name: PrivateSubnet1
```

**Comment by yawboateng** [comment]
@qpaulson  have you  been able to get this to work?

am also seeing an error with version  0.9.4  while trying to validate (coreos/kube-aws/issues/379): 

kube-aws validate --s3-uri s3://buketName

Error: failed to validate node pool #0: invalid cloudformation stack: ValidationError: Template file referenced by https://s3.amazonaws.com/buketName/kube-aws/clusters/ENV-NAME/exported/stacks//stack.json does not exist

I verified my s3 bucket and the stack.json file is created and does exist. I believe the issue here is the extra '/' added to the url before stack.json

**Comment by mumoshu** [comment]
Hi @yawboateng!
`stacks//stack.json` should be `stacks/<your node pool name>/stack.json` if configured correctly.
Probably you're missing `worker.nodePools[].name` in your cluster.yaml?

**Comment by yawboateng** [comment]
Thanks @mumoshu, that was the issue.

**Comment by qpaulson** [comment]
@yawboateng  I had a similar issue.. Because previous versions did not include nodePools, I ended up having to nuke my old cluster.yaml and doing a new kube-aws init then re-populating the cluster.yaml with the config I had before. 

Seems I am only stlightly a little further along than you. :)

**Comment by mumoshu** [comment]
Sorry @qpaulson about that :bow: We're iterating quickly to provide more production-ready solution, therefore `cluster.yaml` changed in a backward-incompatible way.
Perhaps looking into a `diff` of default `cluster.yaml`s between the old and the new versions of kube-aws would help you understand the changes.

**Comment by qpaulson** [comment]
@mumoshu - Thanks so much for your help, its working now!
On a side note, do you know if there is a plan to switch up the etcd orchestration to use the new etcd operator?


```
kubectl --kubeconfig=kubeconfig get nodes
NAME                                            STATUS    AGE
ip-10-51-11-155.ca-central-1.compute.internal   Ready     2h
ip-10-51-13-58.ca-central-1.compute.internal    Ready     2h
ip-10-51-74-234.ca-central-1.compute.internal   Ready     2h
```

Workers:
qkube1-nodepool1-kube-aws-worker - ca-central-1a - running
qkube1-nodepool2-kube-aws-worker - ca-central-1b - running

I only have one controller & etcd server so far, so I'll try and update it from 1 to 3..

**Comment by mumoshu** [comment]
@qpaulson Really glad it worked for you! Thanks for taking much time for this.
I'd appreciate it more if you could submit another issues/feature requests if you find any while the trial.

Regarding the etcd-operator, yes but not very early. I'm not yet used to etcd-operator and self-hosting of k8s and etcd.

**Comment by mumoshu** [comment]
Btw, more concretely; a self-hosted etcd is a pre-requisite for etcd-operator, and bootkube doesn't support deploying a self-hosted etcd cluster (yet).
