### ISSUE TITLE
Etcd option etcdDataVolumeEphemeral set to true result in validation error

### ISSUE THREAD

**Issue by PuKoren** [kubernetes-incubator/kube-aws#446]
Hello there, and thanks for this great project.

kube-aws version used: **0.9.5-rc5**

I try to play a bit with Etcd and wanted to use ephemeral storage:

```yml
etcdCount: 3
etcd:
  subnets:
    - name: KubePrivate1
    - name: KubePrivate2
    - name: KubePrivate3
etcdInstanceType: t2.micro
etcdDataVolumeEphemeral: true
```

However this results in a validation error:
```
kube-aws validate --s3-uri s3://my-bucket
WARNING: instance types "t2.nano" and "t2.micro" are not recommended. See https://github.com/coreos/kube-aws/issues/258 for more information
Validating UserData and stack template...
Error: failed to validate control plane: invalid cloudformation stack: ValidationError: Template format error: Unresolved resource dependencies [Etcd2EBS] in the Resources block of the template
	status code: 400, request id: 22dd5cd2-0fb1-11e7-9bc6-db167fd9ac00
```

kube-aws version used: **0.9.5-rc5**

I'm not familiar with Etcd nor CloudFormation, do you have any guess on this issue , did I do something obviously wrong here?

**Comment by redbaron** [comment]
@PuKoren looks like a bug, validation error should be warning you that t2.micro doesn' have ephemeral storage :)

**Comment by mumoshu** [comment]
Hi Jonathan,
Thanks for trying kube-aws!

In addition to what redbaron pointed out, I might have broken the ephemeral
etcd data volume option in order to support HA etcd. It will persist until
we finish #417.
So; Would you mind turning the option off and use EBS-backed data volumes
as usual in the meantime? Is there any problem which prevents you from
doing so?
I'd appreciate any comment! thx
2017年3月23日(木) 22:21 Maxim Ivanov <notifications@github.com>:

**Comment by PuKoren** [comment]
Thanks for the infos! I turned the option off for now and everything is fine, I just wanted to understand what was going on, so thanks for the answers :+1:
