### ISSUE TITLE
Upgrading your kube-aws cluster to a newer k8s/kube-aws version

### ISSUE THREAD

**Issue by mumoshu** [kubernetes-incubator/kube-aws#455]
This is an umbrella issue to collect various advices regarding how to upgrade kube-aws.

As we're still in pre-1.0, I have not yet taken care of backward compatibility very much. That said, recreating your cluster by running `kube-aws init` and redoing your customizations is the safest way for upgrading (for now).

To be clear, once we've finished "all" the big structural changes to how kube-aws provisions cloudformation stacks and aws resources, starting from v1.0, it will be a matter of just running `kube-aws update` to upgrade kube-aws.

Relevant issue: #311 "Identify missing features to support continuous cluster management"

**Comment by mumoshu** [comment]
https://github.com/kubernetes-incubator/kube-aws/issues/349#issuecomment-288917214

**Comment by mumoshu** [comment]
@pieterlange perhaps [kube-backup](https://github.com/pieterlange/kube-backup) could be an aid to support recreating your cluster with retaining various k8s object, as long as some down time is accepted?

**Comment by mumoshu** [comment]
https://github.com/kubernetes-incubator/kube-aws/issues/311#issuecomment-278833172

**Comment by mumoshu** [comment]
BTW, regardless of it is pre/post 1.0, I personally prefer to temporarily have an extra cluster to achieve blue-green upgrading between kube-aws versions.
Doing so would allow me to roll-back the whole cluster to a previously running cluster when there were any unexpected troubles in the new one.

**Comment by PuKoren** [comment]
@mumoshu it may be difficult to achieve when you also manage your datasources in the Kubernetes cluster, do you recommend to have another cluster for the datasources?

**Comment by mumoshu** [comment]
Yes.

More concretely, I prefer a more mutable, hand-crafted infrastructure for a
k8s cluster dedicated for hosting stateful sets, or utilize AWS-managed
stateful services like RDS.

IMHO, a k8s cluster dedicated for stateful sets would have different reqs
compared to one for stateless pods and services. For example, I don't need
autoscaling there(scarely!) I need flexibility and control on underlying
nodes not to lose data in any circumstance, more than efficiency in cost
and operation.

2017年3月24日(金) 18:21 Jonathan Muller <notifications@github.com>:

@mumoshu <https://github.com/mumoshu> it may be difficult to achieve when
you also manage your datasources in the Kubernetes cluster, do you
recommend to have another cluster for the datasources?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/kubernetes-incubator/kube-aws/issues/455#issuecomment-288972264>,
or mute the thread

**Comment by mumoshu** [comment]
However I'm willing to host everything in one cluster in the future! At
some point in time, having our operational experiences baked into k8s
deployment tools like kube-aws, kops, etc., it will be possible. My
personal idea of only hosting stateless services and blue-green deployments
of clusters are work-arounds until it becomes a reality.
2017年3月24日(金) 22:26 Yusuke KUOKA <ykuoka@gmail.com>:

**Comment by mumoshu** [comment]
Perhaps if we could move a stateful set from one cluster to another within a reasonable down time, recreating a kube-aws cluster won't be a big problem like I imagine

**Comment by mumoshu** [comment]
I don't believe EKS and GKE as of today solves this either. All the K8S clusters are fundamentally equivalent.

Similarly to the belief that you can't literally GUARANTEE that your workloads just work after upgrading your linux kernel or distros, library deps, etc., there SHOULD always be edge-cases and butterfly effects which may affect your workloads.

And the possibility of realizing those edge-cases and butterfly effects should be "relatively" high until K8S gets boring enough.

Some of you don't care upgrading your linux kernel and distros in place today, right?
We need to reach to a such point for K8S to have an enough confidence to just upgrade your clusters in-place without thinking and worrying too much.

So, to us - average human beings - Have an easy and reliable way to roll-back your K8S cluster. Do cluster blue-green deployments to achieve that today. Don't expect for magics.

**Comment by Raffo** [comment]
@mumoshu What we did when I was at Zalando was to update the CloudFormation stack of the cluster and then do a rolling upgrade of the nodes, by adding one node at a time and then killing the others. This worked pretty well since more than a year and it doesn't seem to be so risky as long as you are able to stop the process when something is not right (i.e. nodes can't connect). Creating another cluster is probably less risky, but at this point isn't it better to just create a different Autoscaling Group and start migrating the pods? It seems a bit overkill to have an entirely new cluster.

**Comment by mumoshu** [comment]
@Raffo Thank you for sharing your hard won experience!

I'm glad to hear from you - who I believe one of the most experienced kubernetes-on-aws users.

I'm very much interested in the details.
Would you by any chance mind elaborating a bit more about several points:

> update the CloudFormation stack of the cluster and then do a rolling upgrade of the nodes

Do you mean that you had been updating cfn stacks of etcd, control-plane and node-pool(s) one-by-one? Opposed to a single stack containing all the cluster components(possibly using nested stacks) like what we have in kube-aws today, right?

> This worked pretty well since more than a year and it doesn't seem to be so risky as long as you are able to stop the process when something is not right 

How have you been achieving "stop the process when something is not right"? Triggering a manual rollback of a stack update?

> (i.e. nodes can't connect).

Sounds like what kube-aws do today. Perhaps that would be enough in practice?

> Creating another cluster is probably less risky

Yep, especially when kube-aws introduced a considerable change to stack templates in a release.
But when we have no or small change, it will be completely valid to just roll nodes. I might have been a bit too extreme in that regard.

> different Autoscaling Group and start migrating the pods?

Just for clarification, you mean the exact same thing as your prev sentence "by adding one node at a time and then killing the others." here - am I following you correctly?

**Comment by mumoshu** [comment]
@Raffo BTW - Congrats to your graduation to a new phase(Not sure if you tend to express it like this in your region - the intent is purely a celebration 🎉)

Please let me know if you're interested in becoming one of maintainers of this project 😄 
We do need more drastic improvements like #1112.

Suggestions, reports, and especially code contributions are always welcomed in this project, and hence more maintainers eager to do so are, too 😉

**Comment by Raffo** [comment]
> Do you mean that you had been updating cfn stacks of etcd, control-plane and node-pool(s) one-by-one? Opposed to a single stack containing all the cluster components(possibly using nested stacks) like what we have in kube-aws today, right?

ETCD was always the pet in the setup, updated with a different CloudFormation stack, different tooling and in different times with respect to the clusters: this meant that the lifecycle was completely decoupled from the lifecycle of the cluster, in a similar way a database has a different lifecycle than the web application that it is using. 

> How have you been achieving "stop the process when something is not right"? Triggering a manual rollback of a stack update?

Well, just by not continuing the update, then manual intervention was required. No rollback was implemented. A sufficient testing of test clusters on setups that where not the production one but where sharing exactly the same configuration saved us from any sort of problem. This clearly doesn't work for everyone!

> Yep, especially when kube-aws introduced a considerable change to stack templates in a release.
But when we have no or small change, it will be completely valid to just roll nodes. I might have been a bit too extreme in that regard.

In my opinion we should kind-of stop changing those setups dramatically and the maturity of Kubernetes will be proven when we will be able to stop changing the setup continuously, so yeah there shouldn't be the case that we need to introduce huge changes... we should get boring as soon as possible. 

> Just for clarification, you mean the exact same thing as your prev sentence "by adding one node at a time and then killing the others." here - am I following you correctly?

I actually meant creating a totally different ASG for the workers and attach it to the old master. This would allow for adding a "canary node", then playing with taints would allow to schedule or unschedule pods on such node. In this way the rollback is as simple as taint/toleration. 

> @Raffo BTW - Congrats to your graduation to a new phase(Not sure if you tend to express it like this in your region - the intent is purely a celebration 🎉)

Thank you :-) I actually find myself in the need of setting up Kubernetes on AWS again and I would really be happy to do it with `kube-aws` or other open source tools. 
My requirements, after managing ~60 clusters are actually quite different: 

- I need etcd3 to backup via the snapshot
- I want a single master as I want to save money and operate something simple. I have no need to have an HA master for the things I am doing as long as I can recover the master quickly. 
- I don't want to use CoreOS/ContainerLinux anymore: when shit hits the fan, too many tools are missing when we actually need to debug what is wrong on the node and launching the toolbox is not so cool when things are broken 
- I would love to avoid using Flannel, most of the outages I had to experienced where somehow related to it and hard to debug when you have more than 20 nodes.

> Please let me know if you're interested in becoming one of maintainers of this project 😄
We do need more drastic improvements like #1112. 

I will consider it but I have to take another look, it has been a long time since the last time I really looked at this project, but thanks for asking! :-)

**Comment by mumoshu** [comment]
> ETCD was always the pet in the setup

Sounds like a good assumption.

> this meant that the lifecycle was completely decoupled from the lifecycle of the cluster

Would our etcd cluster be a pet enough once #1112 is landed? Should we go further somehow?

>  A sufficient testing of test clusters on setups that where not the production one but where sharing exactly the same configuration 

I value that, too!
Worth noting in our production guide a lot.

> we should get boring as soon as possible.

Can't agree more! You'll probably see that I have the same feeling if you read the original description of this issue.

> I actually meant creating a totally different ASG for the workers and attach it to the old master.

Interesting. It is a manual process, right? Then, we can do the same with kube-aws today. Seems like a good addition to our guide, too. Thx!

> I don't want to use CoreOS/ContainerLinux anymore: when shit hits the fan, too many tools are missing when we actually need to debug what is wrong on the node and launching the toolbox is not so cool when things are broken

This is something I'm considering these days, too 😃 
I wish AWS releases an AMI tested in combination with certain versions of docker+kubelet, hopefully after they releases EKS.
Which host OS would you choose today?

> I would love to avoid using Flannel

Although I have never happened to experience it in my clusters, interesting.
Time to try #1047!

Thanks for the discussion anyway!
I really appreciate it if you could share your solution once you get there.

**Comment by Raffo** [comment]
> I wish AWS releases an AMI tested in combination with certain versions of docker+kubelet, hopefully after they releases EKS.
Which host OS would you choose today?

As far as I know they are going to use the new Amazon linux. 

> Thanks for the discussion anyway!
I really appreciate it if you could share your solution once you get there.

Absolutely!
