### ISSUE TITLE
Precache container images

### ISSUE THREAD

**Issue by mumoshu** [kubernetes-incubator/kube-aws#505]
If we do it in custom AMIs, boot times of nodes will be shortened considerably.
For example, in my region ap-northeast-1, each worker node takes several minutes to download the hyperkube image required to run kubelet from quay.io.

**Comment by mumoshu** [comment]
rkt is considering to support on-disk sub ACI repos https://github.com/coreos/rkt/issues/695

**Comment by mumoshu** [comment]
If we'd want to bake AMIs, ensure /etc/machine-id is removed
https://groups.google.com/forum/#!topic/coreos-user/_wmOxOfMsEY

**Comment by mumoshu** [comment]
A container linux doc says that users should use `/usr/share/oem/cloud-config.yaml` for customizing machine images but that doesn't apply in this case?

https://coreos.com/os/docs/latest/notes-for-distributors.html#image-customization

**Comment by redbaron** [comment]
I’ve been thinking about speeding up  instance boot, but I was thinking more along the lines of republishing images into local ECR registry and then optionally retagging them into their original names. It looks easier to pull off and less intrusive than rebuilding AMIs

**Comment by c-knowles** [comment]
If we did bake, I think we should go with Packer. Baking it should in theory be less prone to some of the intermittent startup issues we've had. Since those have mostly been fixed already, as @redbaron says just having the images in ECR may help.

**Comment by mumoshu** [comment]
@redbaron Sounds reasonable - Have you tried that yourself? I was too lazy to try myself 😉 
I'm wondering if we could have some adhoc scripts added under the `contrib/` of this project to help users retagging all the images and adding appropriate `*Image` settings to cluster.yaml.
Would it sound good to you?

**Comment by cheungpat** [comment]
I maintain a cluster in ap-southeast-1 and stack update randomly fails because cloudformation timed out waiting for the controller to send SUCCESS signal. It takes well over 10 minutes for a controller to pull images and PT15M is not enough.

Use PT20M solves the problem but it would be great if I can speed up the boot process by caching the Docker images.

I think caching Docker images in the AMI is a better approach because it is faster and there is one less Docker registry to maintain. Using ECR is easier but it requires cluster admin to create a repository for each image and the ECR has to keep up to date with upstream registries. We also need to run `aws ecr get-login` before each pull.

**Comment by redbaron** [comment]
@cheungpat kube-aws is perfectly capable of creating ECR registries for images it is going to republish, so from user perspective no additional would be needed

**Comment by fribourgpierre** [comment]
Hi their,

I am trying to pre pull a large docker image (~5Go) on a custom AMI so that it is then way faster to start (it does not have to pull the image again, and will launch the container in 2s no more).

The point is, that it fails with a very strange issue: the container running on an EC2 with this custom EC2 is very slow when I do that, especially regarding GPU interactions.

What I am doing:

- start a base working AMI on an EC2 instance
- ssh onto it
- run `docker pull myreposiroty/myimage`
- right click on the EC2 instance from AWS console & generate an AMI

My issue is that when my AMI is prepull with my docker image like this,  it then run very very very slow.
If I don't prepull my docker image, then it's running normally, only if i prepull it, the generated a new AMI then my container will be slow like never before.

My docker image use GPU resources and it is based on tensorflow/tensorflow:1.14.0-gpu-py3 image.

Do I have to do something special right after pulling my image on the AMI so that Docker will then run at a normal speed?
It seems that any interaction with the GPU is affected and very slow.

Thanks a lot.
