### ISSUE TITLE
【Feature Suggestion】Provide RESTful API 

### ISSUE THREAD

**Issue by zhangtiny123** [kubernetes-incubator/kube-aws#513]
Hi ,
I think that it's awesome if kube-aws provide a RESTful API.

Something like 
`kube-aws service up`
to start a service, so I can send request to CRUD a cluster or other operations.

**Comment by mumoshu** [comment]
Hi @zhangtiny123, thanks for your interest on kube-aws!
Sounds cool but would you mind sharing us your use-case for that?

**Comment by zhangtiny123** [comment]
@mumoshu  Sorry for the late reply..
I'm building a system which:
1.  Manage multiple k8s clusters for different teams and different regions.
2.  Use the specified credentials to call specified k8s API.

So I want a series of APIs to manage the CRUD operations of clusters, and get the specified k8s API credentials..

What do you think about building this service into kube-aws as a sub-module?

**Comment by mumoshu** [comment]
@zhangtiny123 Thanks for the reply!
I like the idea of creating a multi-tenant web app to manage kube-aws clusters but I'd say that what you would really like to have is not a set of RESTful APIs.

IMHO, just adding RESTful APIs to kube-aws won't add actual values because it seems to imply a web application backed by kube-aws, which stores various configuration files to a local filesystem.
It won't scale very well and it a scalability of that level is acceptable, you can author your web app to invoke kube-aws commands as of today.

What I believe you'd need is an ability, which can also be implemented outside of kube-aws, to store various configurations per cluster per kube-aws version.
A list of configurations would include
* cluster.yaml
* credentials
* cloud-config
* stack-template
* kubeconfig
* etc

If we had such ability, adding RESTful APIs would make sense only when your web app is written in a programming language other than golang, or you'd like not to invoke kube-aws commands but integrate with it via an interface other than `exec`, and you've chosen RESTful API for that.

I'd rather suggest you to draw an overview of the system you're trying to develop, and which part(s) of it can actually be served with kube-aws!

Did my explanation make sense to you? Please feel free to add more replies if necessary.

**Comment by zhangtiny123** [comment]
@mumoshu Yes, it does make sense. Thanks a lot.
