### ISSUE TITLE
Warning in kube-proxy due to unspecified cli parameter

### ISSUE THREAD

**Issue by danielfm** [kubernetes-incubator/kube-aws#588]
I just noticed this log entry in my kube-proxy pods:

```
W0417 15:16:05.916727       1 proxier.go:254] clusterCIDR not specified, unable to distinguish between internal and external traffic
```

It happens because we don't specify the `cluster-cidr` flag to kube-proxy. The question is: should I be worried about this? Is there anything preventing us to specify this flag?

**Comment by mumoshu** [comment]
@danielfm Thanks for bringing this up!
I wasn't aware of it until now but AFAIK, `cluster-cidr` is required when you'd like to access pod IPs/service IPs from outside of a k8s cluster.
For example, If you've run `curl http://<svc/pod ip>` on k8s nodes(rather than pods. You can of course access pod/svc ips among pods), it fails when `cluster-cidr` had been missing.

FYI - relevant upstream issues:
https://github.com/kubernetes/kubeadm/issues/102
https://github.com/kubernetes/kubernetes/issues/36835

**Comment by mumoshu** [comment]
I believe we should fix it as long as we'd like to enable the network bridge feature of k8s to allow accessing pod/svc ips from outside of a k8s cluster.
AFAIK, there's nothing preventing us from specifying the flag.

**Comment by danielfm** [comment]
So it's just a matter of specifying the `cluster-cidr` param to `kube-proxy` with the value of `PodCIDR`?

**Comment by mumoshu** [comment]
AFAIK, yes!
