### ISSUE TITLE
Documentation of long-term managing capabilities

### ISSUE THREAD

**Issue by aholbreich** [kubernetes-incubator/kube-aws#61]
Maybe this is only documentation issue...

But for me it appears to be unclear if this project is meant to support created kubernetes cluster over time or just initial provisioning.
If it is meant to be long term support i miss a docuimetnation (wiki?), that states clearly what to do i common situation like scaling to new number if nodes or another management stuff. 

Lucky, there is propably not so much, but still worth to document it clear in detail for those who not involved in this project so much - but just want to use it. Or step before, get idea of it.

**Comment by pieterlange** [comment]
This project is definitely geared towards full cluster lifecycle issues - initializing takes the most effort right now so it gets the most attention.

We should add a cluster lifecycle management document which describes various runbook scenarios, though i feel like most of those things should happen automatically soon (like manually scaling up (&down) a cluster)

**Comment by mumoshu** [comment]
I'd definitely like to add that kind of documentation to kube-aws.
I'm afraid I can't work on it shortly though and therefore the `help wanted` label 🏷 
In the meantime, I'd like to encourage everyone to contribute by pull requesting with a documentation describing various scenarios in managing kube-aws created clusters.

**Comment by aholbreich** [comment]
@mumoshu first why not use wiki tab of this repo... as main documentation... Community can easily contribute to it.

**Comment by h0tbird** [comment]
+1 for adding extra workers to the initial cluster.

**Comment by mumoshu** [comment]
@aholbreich We're maintaining docs in git because we don't want to diverge our documentations and wiki doesn't allow reviews.

I personally like GitHub wiki. However, currently, everything under the `Documentation/` directory is published to https://coreos.com/kubernetes/docs/latest/kubernetes-on-aws.html after each final release of kube-aws. Therefore using it in kube-aws means we need to maintain diverged docs for coreos.com and wiki, which is what we want to avoid as there are no dedicated maintainer(s) just for docs.

Also AFAIK wiki doesn't allow reviews or pull requests before updating. I'm not yet sure how I could efficiently maintain a wiki which I can't handle when/how/by whom it is updated.

Everything is possible if I could have infinite time and/or more contributors/maintainers but in the mean time, as a primary maintainer, I'd rather like to focus on merging pull requests, tackling big refactorings, implementing new features, in order of priority, because these are what (I believe) only a maintainer can do right now.

Regardless of our current situation, I'd definitely like to have more documentation in kube-aws hence the `help wanted` label.
If anyone is willing to maintain our documentation in any way, or willing to share other maintenance works, I'd appreciate it!
