### ISSUE TITLE
Customized tags by resources.

### ISSUE THREAD

**Issue by erickfaustino** [kubernetes-incubator/kube-aws#653]
Hi! 
I'm using kube-aws to manage my k8s cluster, and it's awesome! Thanks for the project!
I have a question about tags.
Can I customize tags by resource using only the `cluster.yaml` file?
e.g: I want to tag at least my ASGs and ELBs with custom tags, like:
```
Product: SomeProduct
Team: SomeTeam
Env: SomeEnv
```
We use AWS tags heavily to keep a fine grain control about our costs and resources organization. So, for now I need to edit the `control-plane.json.tmpl` and `node-pool.json.tmpl` to customize my tags, but this isn't the better way, because I need to `git checkout --` these files before the `kube-aws update` command. This is a little awkward inside the CI/CD process. If there's a way to do this trough the `cluster.yaml` it will be very helpful. If not, you guys thinks this is a interesting feature? I'd glad to contribute to this.

Thanks!

**Comment by mumoshu** [comment]
@erickfaustino Hi, thanks for using kube-aws 🎉 

I'm interested in your use-case!
How a `cluster.yaml` after your suggested feature enabled would look like?

**Comment by redbaron** [comment]
@erickfaustino,

AWS Cloudformation tags are propagated to resources, created by that CF. You can achieve what you want with following in your `cluster.yaml:
```
stackTags:
  Product: SomeProduct
  Team: SomeTeam
  Env: SomeEnv

```

**Comment by redbaron** [comment]
Regarding `git checkout`  in CI/CD, there is a Git workflow you can follow, which works perfectly well with automation (as long as there are no conflicts :) ). It briefly documented here: https://github.com/kubernetes-incubator/kube-aws/issues/462

**Comment by mumoshu** [comment]
Hi @erickfaustino, just checking in - Did our answer make sense?

**Comment by VinceMD** [comment]
that does not seem to work for me.I've tried adding tags under stackTags. II then render the stack and export to S3, nothing is changed in the CF files. The tags are not added.
I've also tried to update my cluster, same that result: no new tag.
What's the expected behaviour?


I could manually add the tags to my ASG and to my currently running EC2 post installation. New EC2 will get a copy of the tag I've set on the ASG.

**Comment by mumoshu** [comment]
@VinceMD Ah, yes - AFAIK, stack tags are propagated to stack resources when they're created but not updated. It is an expected behavior from a viewpoint of cloudformation, but is indeed confusing!

Closing this as resolved.

JFYI, if we could configure tags not indirectly via stack tags but directly via "Tags" sections of the cfn resources like ASGs and ELBs, it would work even when updating.
If there are strong needs for such use-case, I guess it can be supported in the future.
