### ISSUE TITLE
Updates failing/rebuilding full cluster: enc files, custom DNS, ...

### ISSUE THREAD

**Issue by qpaulson** [kubernetes-incubator/kube-aws#694]
I have built a Jenkins pipeline to "up"/"update" my clusters and I am having some difficulties now that they are actually being updated/used.

There are two main issues I am seeing and they may be related.. 

1: When I make a change, the entire cluster is re-built rather than just updated.
- Even just a small change such as changing the nodePool size from 2 to 3 causes a full rebuild of the cluster

2: Updates are often failing and triggering a UPDATE_ROLLBACK on the cloudformation stack(s).
**- The error here is: 
Group did not stabilize. {current/minSize/maxSize} group size = {0/1/1}. Failed Scaling Activity: One or more target groups not found. Validating load balancer configuration failed.**
- The only way i've been able to resolve this is to completely delete the stack and re-run the pipeline to create a net new cluster.

The Jenkins Pipeline is storing all of the certs, kubeconfig & Certificates in Hashicorp Vault.
When an update is triggered I fetch the certificates from the vault and put them back in the correct locations.. 

I suspect this is the main cause for the re-build as there must be a change in timestamps or some file that represents a full-rebuild.

Any ideas what may be causing this to happen?  Is it not ok to store the cluster artifacts into a Vault/data-store ?

Thank you in advance for any responses.

**Comment by mumoshu** [comment]
Hi @qpaulson, thanks as always for trying kube-aws!
What an interesting thing you're working on 😄 

Anyway, what looked suspicious to me this part:

> The Jenkins Pipeline is storing all of the certs, kubeconfig & Certificates in Hashicorp Vault.
> When an update is triggered I fetch the certificates from the vault and put them back in the correct locations..

Are you sure you're also storing `*.pem.enc` files? enc files are encrypted versions of corresponding pem files, which must be persisted due to the nature of AWS KMS used to encrypt kube-aws assets.
KMS produces different cipher(=persisted as an enc file) each time it encrypts an asset(=e.g. a pem file in kube-aws). Accordingly, if you are not missing pem files in your Vault but enc files, every `kube-aws update` causes a full rebuild of an k8s cluster due to recreated/different enc files.

**Comment by qpaulson** [comment]
Thank you.. I am currently not storing the .enc files as I see its regenerating them each time.. But based on what you are saying that all makes sense now.   I will add this to my process and see if it helps. 


I believe I've uncovered why my updates fail as well.. Its because my etcd nodes are resolving their DNS names to their "public" ip's which wont work.  It should be resolving to their private IP's. 

I have mapPublicIPs: false in my configuration file, has something changed and this parameter no longer works?

**Comment:**
# Uncomment to provision nodes without a public IP. This assumes your VPC route table is setup to route to the internet via a NAT gateway.
# If you did not set vpcId and routeTableId the cluster will not bootstrap.

**Comment by mumoshu** [comment]
@qpaulson Sorry If I'm not following you correctly but AFAIK `mapPublicIPs` had been working only for worker and controller nodes but not etcd nodes, right?

Anyway, etcd hostnames should certainly be resolved to their private IPs. By default, we use Elastic IP + Amazon DNS for that. Amazon DNS in your VPC(at the very first of VPC CIDR, 10.0.0.1 or so), surprisingly, resolves public hostnames(stabilized by Elastic IPs) to private IPs.

So, several questions to clarify next action(s):

* Could you verify you point your DNS to Amazon DNS?
* If you're relying on your own DNS server, could you forward your DNS queries against e.g. `<region>.compute.amazonaws.com` for regions other than us-east-1, to Amazon DNS?
* If you'd like not to rely on EIPs and Amazon DNS, it is not yet my recommendation but could you try `etcd.memberIdentityProvider: eni`? The eni provider uses ENIs and its private IPs instead for network identities of etcd nodes.

**Comment by qpaulson** [comment]
@mumoshu Yes, we are using a DNS forwarder that forwards our internal queries to our internal DNS and the Amazon queries to the Amazon DNS.

a dig on the aws DNS that is configured in /etc/etcd-environment resolves to the external IP.

I will try the eni method, but EXPERIMENTAL scares me a bit.

**Comment by qpaulson** [comment]
@mumoshu  The cluster is working now with the eni mode set.  I also now have the .enc files being stored in the VAULT as well and the updates are working as expected!. 

Appreciate your assistance once again!.

**Comment by mumoshu** [comment]
@qpaulson 

> Yes, we are using a DNS forwarder that forwards our internal queries to our internal DNS and the Amazon queries to the Amazon DNS.

Just wondering but are you sure that the Amazon DNS here should be the one sitting inside your VPC, at the very beginning of ip range of the VPC?
For me, it seems like you're forwarding queries to `ca-central-1.compute.amazonaws.com` to NS servers provided by Route 53, which is something other than Amazon DNS?

**Comment by mumoshu** [comment]
@qpaulson Anyway, glad to hear it worked 👍 
FYI, why I call the eni provider experimental is that, it just rely on moving parts more than the eip provider. Under the hood, it attaches an ENI as the secondary NIC per etcd node and disables the automatically-assigned primary NIC on the etcd node so that each node can communicate via the well-known IPs associated to ENIs=secondary nics.

Anyway, it would work without problem until you do something I didn't expect 😉

**Comment by mumoshu** [comment]
Closing this as resolved - @qpaulson Please feel free to call me if you'd like to use the EIP strategy by any chance. It should work without problems when a custom DNS is configured properly.

**Comment by yanhongwang** [comment]
Hello @mumoshu 

I meet the same error message like @qpaulson 
Since that update is failed. And I run "kube-aws update" again.
It shows below:

**Error: Error updating cluster: error updating cloudformation stack: ValidationError: Stack:arn:aws:cloudformation:eu-central-1:791508175888:stack/ifap/762778d0-d514-11e7-9c5f-503f2ad2e536 is in UPDATE_ROLLBACK_FAILED state and can not be updated.
	status code: 400, request id: 2454da72-a76b-11e8-b927-b94c2a959187**

Is that possible to fix?
Or I have to delete cluster to create new one?
Thanks very much.

**Comment by kevtaylor** [comment]
@yanhongwang You can go to the AWS cloudformation console and select the stack and force the stack to continue the rollback until it is clean again
