### ISSUE TITLE
Feedback on IAM role creation

### ISSUE THREAD

**Issue by c-knowles** [kubernetes-incubator/kube-aws#698]
Following up on @Fsero's nice work from https://github.com/kubernetes-incubator/kube-aws/pull/607. So far it's mostly been exactly what we need. I hit a couple of doc issues I think we should improve:

1. `cluster.yaml` mentions `{"AWS::StackName"}-{"AWS::Region"}-yourManagedRole` a couple of times but this was changed in https://github.com/kubernetes-incubator/kube-aws/pull/607 to not include the stack name. I think the recommendation should be to include the stack name otherwise we end up with fairly generic `eu-west-1-poolname-role` role names.
1. The validation for the character limit is still in place prefixed with stack name - [see here](https://github.com/kubernetes-incubator/kube-aws/blob/1f08f3bb7ebe12cca738ba25df42263ca077cc3a/cfnresource/naming.go#L8)
1. It was not totally obvious to me at first that the role names get exported from the node pool stacks as well as the root stack. The exports from the node pools look like `k8s-dev-PoolName-Y1WKSC7JU6JS-WorkerIAMRoleArn` but the one from the root looks like `k8s-dev-NodePoolPoolNameWorkerIAMRoleArn` which is obviously easier to reference
1. There's warnings to not use the documented settings as below but the settings recommended don't seem to work (both controller and worker settings under `iam` seem to not do anything:

```
WARN: worker.nodePools[].managedIamRoleName is deprecated and will be removed in v0.9.7. Please use worker.nodePools[].iam.managedRoleName instead
WARN: controller.managedIamRoleName is deprecated and will be removed in v0.9.7. Please use controller.iam.managedIamRoleName instead
```

Then one question for @Fsero - given that with an export we can reference the ARN of the worker pool roles, what does overriding the unique ID name of the actual role provide? I'd assume any references would use the ARN export and not reference the name directly.

**Comment by c-knowles** [comment]
I think I answered my own question from the final part of the above. Even if the exported role name is consistent, AWS still produces an error if the underlying ARN changes and another stack depends on the exported name. I wonder if they will change that behaviour at some point so it can be a bit more dynamic.

**Comment by Fsero** [comment]
Hi @c-knowles! Thanks for your comments :)

Let us review them one by one

> cluster.yaml mentions {"AWS::StackName"}-{"AWS::Region"}-yourManagedRole a couple of times but this was changed in #607 to not include the stack name. I think the recommendation should be to include the stack name otherwise we end up with fairly generic eu-west-1-poolname-role role names.

About the mentions on cluster.yaml that is a bug (i probably introduced that so sorry about that) and should be fixed. However about including the stack name i disagree, if we include the stack name with the current cloudformation structure a role will be like MyCluster-$RANDOMIDFROMCFN-eu-west-1-poolname-role which will not be stable and not predictable.

As you commented later you can use ImportValue in Cloudformation to retrieve role name as long as you are in the same region. I use kube2iam in my kube-aws cluster and i have applications that assumes a role in other region than the cluster is deployed, because kube2iam need to trust the kube-aws cluster's role i need it predictable since i cannot retrieve role name using import value (target role is in other region)

however i will not argue against change the naming scheme to {"AWS::NestedStackName"}-{"AWS::Region"}-$NAME that will generate roles like MyCluster-eu-west-1-$NAME

> The validation for the character limit is still in place prefixed with stack name - see here

yes, that should be addressed. If you like my proposal of changing the scheme for {"AWS::NestedStackName"}-{"AWS::Region"}-yourManagedRole i can modify the validation for that scheme or at the very least just check the length.

> It was not totally obvious to me at first that the role names get exported from the node pool stacks as well as the root stack. The exports from the node pools look like k8s-dev-PoolName-Y1WKSC7JU6JS-WorkerIAMRoleArn but the one from the root looks like k8s-dev-NodePoolPoolNameWorkerIAMRoleArn which is obviously easier to reference

Do you prefer that we dropped exports in nested stacks and we only leave the exports in the root stack?

i consider this also a bug since as you said k8s-dev-NodePoolPoolNameWorkerIAMRoleArn it's easier to reference.

> There's warnings to not use the documented settings as below but the settings recommended don't seem to work (both controller and worker settings under iam seem to not do anything: WARN: worker.nodePools[].managedIamRoleName is deprecated and will be removed in v0.9.7. Please use worker.nodePools[].iam.managedRoleName instead

That warning message is outdated from a previous revision, it should say worker.nodePools[].iam.name i consider that also a bug.

> given that with an export we can reference the ARN of the worker pool roles, what does overriding the unique ID name of the actual role provide? I'd assume any references would use the ARN export and not reference the name directly.

My use case is related to trust kube-aws cluster roles in other regions where i cannot use directly the export.

@c-knowles great job uncovering this edge cases and some bugs, i'm happy to fix them :)

**Comment by c-knowles** [comment]
@Fsero Thanks for you reply. Ah, I need to clarify - by `stack name` I actually meant the kube-aws root stack name which is just the `clusterName` from `cluster.yaml`. I definitely understand why you don't want it to vary and agree with you so we are saying the same thing I think. The problem I encountered is that if the user names the role `pool-a` it ends up with a particular generic IAM role name which will conflict if they have multiple clusters in the same account/region.

If we change to `NestedStackName`, then my assumption is that the role name in `cluster.yaml` could be just `worker-role` and then we'd end up with an IAM role of `k8s-dev-PoolA-worker-role` assuming the cluster name is `k8s-dev` and the pool name is `pool-A`.

> Do you prefer that we dropped exports in nested stacks and we only leave the exports in the root stack?

I don't mind either way, even just updating the docs markdown to be explicit would be fine I think. If you consider it a bug then we should drop the nested exports probably if that's possible.

> given that with an export we can reference the ARN of the worker pool roles, what does overriding the unique ID name of the actual role provide? I'd assume any references would use the ARN export and not reference the name directly.

Understood, I also found the parts of the AWS docs that talk about them binding to the underlying user ID of the principals when allowing the assume role, [here](http://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_elements.html#Principal). In our case, I'm not keen to bind a stack that is external to the k8s cluster to the exact user IDs created by AWS in the k8s stack. I'm not sure if you found a solution for that? Assuming I wish for kube-aws to manage it's own role, I found no decent solution due to AWS not allowing principal wildcards (I understand there's a privilege escalation path here, just in our case it's an entirely separate account so the risk is minimal).
