### ISSUE TITLE
Expand list of project members

### ISSUE THREAD

**Issue by redbaron** [kubernetes-incubator/kube-aws#717]
@mumoshu , with you being more and more busy, would you mind adding long standing contributors to members list with commit rights so that project can continue to evolve?

I'd propose @danielfm, @c-knowles and @camilb to be added.

**Comment by mumoshu** [comment]
@redbaron Hey, thank you very much for your suggestion! I believe you meant @danielfm, @c-knowles and @camilb but anyway,
yes, I definitely like to welcome more maintainers for the reason of your consideration 😄 

---

Though it could sound obvious, would you mind letting me add something as a maintainer?

If I could wish every maintainer to follow one thing, it would be "begin with github issue(s)", so that we won't lose track of where we as the whole kube-aws community are going.

Also, I encourage every maintainer not to hesitate to add new experimental features, improvements, fixes as long as they seems general enough so that our users can benefit from them. In other words, I believe you. Once you become a maintainer, please improve kube-aws as you like. You maintainer should also benefit from having more control over this project(in return for the time you spend on it ⌛️), and I believe your users can benefit from those changes in some ways.

Btw, regardless of my encouragement, please feel free to ask me and @redbaron 😃 for reviews, comments, advices, etc. We're here to help you.

---

@danielfm @c-knowles @camilb WDYT?

**Comment by mumoshu** [comment]
@redbaron Btw, just wondering but did I look absent these days?
It is true that I have been busy recently to improve cluster-autoscaler but that is to bring a reliable cluster-autoscaling feature into kube-aws! So, I'm still committed to maintain and improve kube-aws 👍

**Comment by c-knowles** [comment]
Happy to be on the list, I will adhere to any community rules we have. I was thinking that unless it's a very minor issue maybe the PR creator should not be the one to merge to prevent us each merging their own pieces with potential conflicts and architecture issue. Could we use the kubernetes issue helper robots or are those only for core projects?

**Comment by redbaron** [comment]
I am afraid to merge anything but simplest PRs because there is no automation in testing. Starting to introduce even basic CI is something which can help a lot. @mumoshu does kubernetes-incubator provide any facilities for that, or we need to come up with something on our own?

**Comment by danielfm** [comment]
@mumoshu @redbaron as a kube-aws user myself, I certainly don't have to have commit rights in order to continue contributing, but I really appreciate the gesture. Count me in. :)

**Comment by mumoshu** [comment]
> I am afraid to merge anything but simplest PRs because there is no automation in testing

So am I 😉 

>  @mumoshu does kubernetes-incubator provide any facilities for that, or we need to come up with something on our own?

No, kubernetes-incubator seems to not provide anything like that, unfortunately 😢 
I'm recently trying to contact my potential sponsor outside of my company if he could donate AWS credit so that we can afford the test-infra for kube-aws, including a CI system and test clusters, bots, etc.
Any support on this is welcomed.

**Comment by mikedanese** [comment]
cc @spxtr @rmmh

**Comment by spxtr** [comment]
> How do we enable k8s-bot on this repo?

It's already enabled for all repos in kubernetes-incubator, which you can verify by noting that all PRs are labelled with CLA labels. If you want further commands to work, such as /lgtm, then you need to add an entry to [the prow config](https://github.com/kubernetes/test-infra/blob/master/prow/plugins.yaml) for this repo. If you want a submit queue... that's more difficult and I'm not sure how to set it up on a new repo.

**Comment by mumoshu** [comment]
@mikedanese @spxtr Thanks for the info!

@c-knowles Which k8s-bot commands would you like to use in this repo? Only /lgtm?

**Comment by c-knowles** [comment]
@mumoshu yeah I think we'd be happy with that for now, it would be good to have the other capabilities.

Regarding testing, could we consider [LocalStack](https://github.com/atlassian/localstack) along with one of the CIs which is free for open source? Does anyone have experience with LocalStack?

**Comment by mumoshu** [comment]
@c-knowles Just curious but do you mean to write tests which utilizes localstack as fake aws for each bash snipped spread over kube-aws' cloud-configs?
However, afaik, localstack doesn't support e.g. AWS auto-scaling, elb so that it can't be utilized everywhere.

**Comment by mumoshu** [comment]
@mikedanese @spxtr Thanks to your support, I've managed to enable /lgtm on this repo 🎉

**Comment by mumoshu** [comment]
Annoucing that @c-knowles and @danielfm have been just invited as collaborators of this repo with write permissions as they expressed willingness to do so 🎉

**Comment by camilb** [comment]
@mumoshu If I can help in any way, I'll be glad to do it. Initially didn't see my name on the list.

**Comment by mumoshu** [comment]
@camilb Thanks! I've sent an invitation to you for becoming a collaborator w/ write access to this repo.

**Comment by mumoshu** [comment]
Closing this as done. Please feel free to open another issues when you think someone is eligible to become a new maintainer.
