### ISSUE TITLE
Find what version of kube-aws generated a config / cluster?

### ISSUE THREAD

**Issue by martindanko** [kubernetes-incubator/kube-aws#736]
How can one discover what version kube-aws binary generated a cluster.yaml configuration?

Thanks.

**Comment by mumoshu** [comment]
@martindanko Hi!
Unfortunately, there's no easy way to discover it for now 😢 

For this specific case, we probably can find out the version by looking into your cluster.yaml if you could share it.

For longer term, would it help if there is a yaml comment like:
```yaml
# This file is generated by kube-aws (version number here)
```
in cluster.yaml?

**Comment by c-knowles** [comment]
Could we put the version of kube-aws used in the stack tags or parameters? It would represent the last version used to update the cluster. It might help a bit for the `cluster.yaml` use case as well if we keep new default config uncommented there because older versions will not recognise that config and produce an error showing an update is needed. Perhaps we could also add something like `apiVersion` to the cluster.yaml so we can start to better define the schema of each and changes between?

**Comment by mumoshu** [comment]
Yes, putting the version in stacks would be very helpful 👍 

`apiVersion` sounds awesome from user's perspective. I'm still wondering how `apiVersion` is implemented. Would it be something like all the historical versions of the schema maintained in kube-aws' code-base?
