### ISSUE TITLE
Ability to provide more fine-grained cluster updates

### ISSUE THREAD

**Issue by ytsarev** [kubernetes-incubator/kube-aws#783]
Currently during delivering updates to the cluster with `kube-aws update` all cluster is getting redeployed starting from Etcd nodes.

When I want to deliver some simple update to worker nodes it is quite an overhead.

I would like to have ability to perform updates to worker nodes only, preferably to target worker pool.

**Comment by ytsarev** [comment]
Uhm, just now kube-aws did exactly what i wanted - provided update to worker nodes only when i did only worker related changes. Can local gurus point me to a code responsible for that ? :)

**Comment by danielfm** [comment]
I've seen this in cases where I don't specify the `amiId` parameter.

When unspecified, kube-aws will check which is the latest AMI for the given release channel and use that in the upgrade. If the AMI currently in use by your instances don't happen to be the latest one, all your nodes are going to be updated.

That's why I personally keep the AMI ID fixed in my `cluster.yaml`.

**Comment by ytsarev** [comment]
Thanks a lot for the hint!

**Comment by mumoshu** [comment]
@danielfm @ytsarev Ah, good point!

Perhaps kube-aws would better fill the latest AMI ID into `amiId` at the time of writing cluster.yaml?

**Comment by redbaron** [comment]
> Perhaps kube-aws would better fill the latest AMI ID into amiId at the time of writing cluster.yaml?

May I ask for a `render` commandline switch to retain previous behaviour? Otherwise it is going to cause constant merge conflicts :(

use of coreos channels works best for us,  because coreos built in autoupgrade doesn’t work well with Kubernetes and ASG, so periodically running kube-awe update is our way t keep up with security updates

**Comment by ytsarev** [comment]
@redbaron what is your schedule for running updates ?

**Comment by tyrannasaurusbanks** [comment]
hey @ytsarev, I worked with redbaron - updates are sporadic right now - we roll when there are new features we'd like to introduce. But the goal for our automation would be a daily roll - we're getting good feedback from developers consuming our clusters when we roll often as it helps them stay focused/aware of involuntary (on their part) cluster disruptions.

Sorry for the lateness of this answer - just browsing issues and saw this.

**Comment by ytsarev** [comment]
@tyrannasaurusbanks sounds good, thanks!
