### ISSUE TITLE
Sync TLS Bootstrap cluster roles with upstream

### ISSUE THREAD

**Issue by redbaron** [kubernetes-incubator/kube-aws#808]
Official roles just landed to Kubernetes master: https://github.com/kubernetes/kubernetes/pull/49284/files

See no reason not to replicate them in kube-aws

**Comment by mumoshu** [comment]
@redbaron Thanks for the info 👍 

@danielfm Anyway, I see three deltas from what we have now:

1. `rbac.authorization.kubernetes.io/autoupdate: "true"`
2. Seemingly more complete, longer cluster role name like `system:certificates.k8s.io:certificatesigningrequests:nodeclient`
3. The `kubernetes.io/bootstrapping: rbac-defaults` label

I can't figure out why those three things are required.
Not saying it is unnecessary, at all, but just curious because I don't know - do you know what values will those 3 things add?

**Comment by danielfm** [comment]
I also have no idea... I'd need to dig into the source code to find out.

**Comment by mumoshu** [comment]
Could anyone pick this up?
