### ISSUE TITLE
Cluster upgrade causes entire cluster to relaunch

### ISSUE THREAD

**Issue by drywheat** [kubernetes-incubator/kube-aws#825]
**Goal:** Add another node pool to an existing k8s cluster created using `kube-aws`.
**Problem:** All of the my CF stacks/servers were updated/re-launched (etcd/controllers/workers).

### Versions

**kube-aws:** v0.9.7
**kubernetes:** "v1.6.3+coreos.0

### Actions Taken

This morning I added another node pool config entry to my `cluster.yaml` file, validated it against S3 and attempted to perform a simple update (`kube-aws update --s3-uri s3://kube-aws-bucket`).

### Observed Behavior

Two very strange things happened during this update:

1. Every server in my cluster was replaced.

    I expected that this update would create a new CF stack and then launch my additional node pool.  It did do that but only after updating my control-plane and existing node pool stacks. Oddly enough, I ran a test on a separate, new cluster prior to this update and that behaved as expected. Now I'm thinking, "Is there something wrong with the configs for my existing cluster?"

2. All of the apps in my cluster that rely on basic Kubernetes DNS support all crashed.

    After the cluster update was completed, `kube-dns` was left in a wonky state that caused the services 'n' such to fail. I was finally able to get DNS running after reading https://github.com/kubernetes-incubator/kube-aws/issues/532 and following the instructions there. What's more, I had to delete service account tokens in various other NSs because of the same permission problems.

### Context

I use a single S3 bucket to save all of the configs for my various clusters (e.g. dev, experimental, prod), call it `kube-aws-bucket`. Everytime I update one of my clusters I point it at the bucket instead of a specific folder.

```
# inside dev-cluster dir
kube-aws update --s3-uri s3://kube-aws-bucket/ 

# inside experimental-cluster dir
kube-aws update --s3-uri s3://kube-aws-bucket/

# inside prod-cluster dir 
kube-aws update --s3-uri s3://kube-aws-bucket/
```

I noticed that `kube-aws` will create a folder structure inside of that bucket that looks like it's capable of managing several clusters (e.g. `kube-aws-bucket -> kube-aws -> clusters -> (dev|prod|experimental)-cluster`). Is this approach wrong? Should I be pointing the tool in each case at a _specific folder in that bucket_?

I would like to selectively update pieces of my production cluster w/o having to worry about it bringing down some/all services. At this point, I don't know if this is something with the tool, the way I'm using it or the underlying kubernetes components.

**Comment by danielfm** [comment]
Did you specify the `amiId` parameter in `cluster.yaml`, or did you leave it blank?

**Comment by drywheat** [comment]
It is currently blank. OMG, is that why I'm seeing this cluster update?

**Comment by danielfm** [comment]
> Oddly enough, I ran a test on a separate, new cluster prior to this update and that behaved as expected.

This is why I asked. Your production cluster might be using an older AMI, and when you issued `kube-aws update`, kube-aws used the latest AMI (since you left it blank in `cluster.yaml`), which lead all instances to be replaced.

When you created your test cluster, that cluster probably used the latest AMI, and this explains why `kube-aws update`ing it did not replace all instances.

This is a known behavior, but we need to make this less obscure by properly documenting this in `cluster.yaml`, or by making `amiId` mandatory.

**Comment by danielfm** [comment]
@mumoshu @redbaron what do you guys think would be the correct way to avoid this kind of mistake? My vote would be to make `amiId` mandatory, and have `kube-aws init` to automatically set this field in `cluster.yaml`.

**Comment by drywheat** [comment]
Thanks @danielfm, that solves my first problem. Do you have any notion what might be causing the latter problem?

**Comment by danielfm** [comment]
@drywheat First, in order to avoid having all kube-dns pods deleted at the same time during cluster updates, I'd recommend you to create a [Pod Disruption Budget](https://kubernetes.io/docs/tasks/administer-cluster/configure-pod-disruption-budget/) (so you can specify the minimum number of kube-dns pods to be up during voluntary evictions), and enable the Node Draining feature in `cluster.yaml`.

With respect to the errors in service accounts, I don't see how this could happen unless you somehow re-generated your credentials (with `kube-aws render credentials --generate-ca`) somewhere between creating your production cluster and updating it.

**Comment by drywheat** [comment]
Is it perfectly fine to use the same S3 bucket for all clusters? Will `kube-aws` manage the structure perfectly fine using folders?

**Comment by danielfm** [comment]
Yes, data for each cluster will be stored in its own sub-directory in S3.

**Comment by drywheat** [comment]
I just verified that the userdata files for my control plan entities did change during my update. A diff between the older and newer versions of each respective file revealed that the credentials were the pieces of data that shifted.

I honestly have no idea how those credentials changed because I don't recall re-rendering them, but that's on me.

**Comment by mumoshu** [comment]
Hi @drywheat, would you mind confirming if you had removed `credentials/*.pem.enc` files?

They are cache files of corresponding pem files which are used to prevent a complete cluster roll-over due to re-encryptions of pem files.

A re-encryption results in different ciphertexts. In other words, KMS encryptions produce different ciphertexts for same contents. So for example, removing `*.pem.enc` files results in a complete roll-over, regardless of whether pem files themselves are updated or not.

Relevant issues: #107 #694

**Comment by drywheat** [comment]
I had saved all of my credentials (`*.pem`/`*.pem.enc` files) in a gzipped tarball that I stored in a secure location. I pulled down a new copy of that archive and verified that it has all of files.  Furthermore, it had the same exact files that I'm using locally. At this point I'm thinking that I must have update my credentials prior to creating that archive.

If the credentials were checked into version control, which I would never do, I would easily be able to spot changes if there were to occur. So last night I decided to create a `SHA256SUMS` file will a digest of each credentials so that I can sanity-check what's in `credentials/` prior to running an update. That checksum file is checked into my vcs.

**Comment by redbaron** [comment]
Currently if you rotate apiserver.pem you also need to remove every serviceaccount secret in every namespace and then restart all pods which were using deleted secrets

**Comment by drywheat** [comment]
Thanks y'all, I think I have a good understanding about what happened here and I've taken steps to prevent them from happening again.

**Comment by mumoshu** [comment]
@drywheat Thanks for the valuable info 👍 

JFYI, there are `credentials/*.pem.fingerprint` files which contains sha256 sum of corresponding pem files. I hope they can be used for sanity-checking.

Ref: https://github.com/kubernetes-incubator/kube-aws/blob/master/core/controlplane/config/credential.go#L169-L173

**Comment by drywheat** [comment]
That's good to know and I do think it makes sense to generate those digests.

Have y'all considered refining your `credentials/.gitignore` file so that it only excludes `*.pem*`, files and tell users to save the fingerprints for PEMs? That way they can cross-check their credentials before executing an update.

It turns out another member of my team had a separate set of credentials from a different cluster that was applied to the one in question in this issue. That is what ultimately caused the unwanted credential swap in our case.
