### ISSUE TITLE
Provide support for encrypted State buckets

### ISSUE THREAD

**Issue by sathiyas** [kubernetes-incubator/kube-aws#831]
Currently kube-aws gets a 403 when using a bucket with encryption enforced. Should be able to support buckets with encryption policy (KMS/AES256)

**Comment by mumoshu** [comment]
@sathiyas Thanks for the feedback 👍 

Honestly I'm not an expert in managing encrypted buckets.
So, would you mind helping me understand following things?

* Why 403? Probably you've enforced server-side encryption on every newly uploaded object via a bucket policy like the one described in [the aws doc](http://docs.aws.amazon.com/AmazonS3/latest/dev/UsingKMSEncryption.html), right?
* If that's the case; the next question is whether you want to bring your own CMK(Customer Managed Key) used for encryption, or want S3 to automatically generate/manage one for you. Perhaps supporting only the latter would be ok for you?

**Comment by sathiyas** [comment]
@mumoshu Correct, many enterprises require all S3 buckets to enforce encryption on every uploaded object. So this support will be enviable for many financial/health care industries

I think supporting the S3 managed AES256 will be a good start. KMS can be a future request. Taking another parameter in the cluster.yaml with an encrypt=true flag and adding the support in the API call will be great

Thx for looking into it.

**Comment by mumoshu** [comment]
@sathiyas I'm just thinking what to do on kube-aws for this 🤔 

If you completely rely on the default encryption settings per bucket to enforce SSE, kube-aws will just work. The problem is that the bucket policy rejects any PUT request without the `x-amz-server-side-encryption` header, even when the default encryption is configured to enforce SSE.
So - in other words, I guess you can just [configure a default encryption on your S3 bucket](https://docs.aws.amazon.com/ja_jp/AmazonS3/latest/dev/bucket-encryption.html#bucket-encryption-update-bucket-policy) while removing the bucket policy.
As there's no way to skip encryption via the `x-amz-server-side-encryption` header when the default encryption is configured, you can safely remove the bucket policy without worrying about unencrypted objects being stored on the bucket.

Am I correct? Then, [can you just (1) configure the default encryption on your S3 bucket and (2) remove the bucket policy](https://docs.aws.amazon.com/ja_jp/AmazonS3/latest/dev/bucket-encryption.html#bucket-encryption-how-to-set-up), and try kube-aws again?

**Comment by mumoshu** [comment]
One possible gotcha is that, if you've configured your bucket to enforce SSE with `aws:kms` via the default encryption, you'd probably like to forbid overriding the default encryption with `AES256`, right?

For that, I guess you can use the bucket policy like this:

```json
{
  "Version": "2012-10-17",
  "Id": "PutObjPolicy",
  "Statement": [
    {
      "Sid": "DenyIncorrectEncryptionHeader",
      "Effect": "Deny",
      "Principal": "*",
      "Action": "s3:PutObject",
      "Resource": "arn:aws:s3:::YourBucket/*",
      "Condition": {
        "StringEquals": {
          "s3:x-amz-server-side-encryption": "AES256"
        }
      }
    }
  ]
}
```

So that both omitting `x-amz-server-side-encryption` and explicitly setting it to `aws:kms` results in triggering the default encryption(=`aws:kms`), while explicitly setting it to `AES256` results in 403.

**Comment by mumoshu** [comment]
Similarly, if you'd like kube-aws to use `aws:kms` for `x-amz-server-side-encryption` and a specific KMS key for `x-amz-server-side-encryption-aws-kms-key-id`, you can configure your bucket's default encryption with those settings, while rejecting any encryption and any key other than than the defaults by a bucket policy:

```json
{
  "Version": "2012-10-17",
  "Id": "PutObjPolicy",
  "Statement": [
    {
      "Sid": "DenyIncorrectEncryptionKey1",
      "Effect": "Deny",
      "Principal": "*",
      "Action": "s3:PutObject",
      "Resource": "arn:aws:s3:::YourBucket/*",
      "Condition": {
        "StringEquals": {
          "s3:x-amz-server-side-encryption-aws-kms-key-id": "non-default-key-1-id"
        }
      }
    },
    {
      "Sid": "DenyIncorrectEncryptionKey2",
      "Effect": "Deny",
      "Principal": "*",
      "Action": "s3:PutObject",
      "Resource": "arn:aws:s3:::YourBucket/*",
      "Condition": {
        "StringEquals": {
          "s3:x-amz-server-side-encryption-aws-kms-key-id": "non-default-key-2-id"
        }
      }
    }
  ]
}
```

**Comment by mumoshu** [comment]
Ok - so, even though you can enforce SSE completely from S3-side, our awscli run on kube-aws nodes must be configured specifically to meet the prerequisite of SSE? 🤔 

```
Nov 22 07:44:38 ip-10-0-0-14.ap-northeast-1.compute.internal bash[836]: [   43.394212] awscli[5]: download failed: s3://mybucket-awskms/kube-aws/clusters/k8s3/exported/stacks/control-plane/userdata-etcd-17b8f44627f965ab81b50e4731f35a6d26bebe1f4f46be46dc0bb9f7ea944f86 to var/run/coreos/userdata-etcd An error occurred (InvalidArgument) when calling the GetObject operation: Requests specifying Server Side Encryption with AWS KMS managed keys require AWS Signature Version 4. You can enable AWS Signature Version 4 by running the command:
```

**Comment by mumoshu** [comment]
@sathiyas Based on my research, #1023 would probably be the only necessary change on kube-aws side. Would you mind confirming my ideas and checking it if it works for you? 😃

**Comment by mumoshu** [comment]
@sathiyas Or perhaps you'd like kube-aws to explicitly set `x-amz-server-side-encryption` and `x-amz-server-side-encryption-aws-kms-key-id` to keep your bucket policy simple?
