### ISSUE TITLE
Use CloudFormation custom resource to do `kubectl apply` natively

### ISSUE THREAD

**Issue by redbaron** [kubernetes-incubator/kube-aws#898]
We install manifests from `install-kube-system` script which is part of controller startup procedure. This have following drawbacks:
 - All controllers unnecessary need to be rolled when manifest updates which is slow.
 - Resources which used to be installed, but not anymore remain hanging in existing clusters
 - Any future CF ChangeSet preview we implement makes diff hidden

We can utilise CloudFormation custom resource (implemented as Lambda function), which then does `kubectl apply` on install/update and `kubectl delete` on remove. This solves all the drawbacks of current method

**Comment by c-knowles** [comment]
I had an edge case which came up yesterday that think this may also solve?
- emergency patch something that is in the controller install, patch outside of kube-aws, in my case the patch content was not supported yet by kube-aws
- controllers scale and then emergency patch is overridden when new controller starts

**Comment by redbaron** [comment]
Yes, it would solve it as well. Controllers coming up will not be applying anything

**Comment by mumoshu** [comment]
Thanks, this is certainly what I'd like to try!

Several questions probably needed before POCing:

* I'm not very happy with introducing an another programming language in kube-aws for this. Can  we develop it based on [aws-lambda-go from eawsy](https://www.reddit.com/r/golang/comments/58zra4/finally_vanilla_go_on_aws_lambda_no_serverless/)?
   * Btw, I suppose that aws-lambda-go or alike would be the official way to use golang apps on lambda sooner or later.
* How should the lambda function serving custom resources should be deployed? Would it be ok to include it in the root stack?

**Comment by fsenart** [comment]
Hi guys, just want to let you know that [we](https://gitter.im/eawsy/bavardage) remain at your disposal if you need any help using [aws-lambda-go-shim](https://github.com/eawsy/aws-lambda-go-shim). We also provide a full featured CloudFormation custom resource [lib](https://github.com/eawsy/aws-cloudformation-go-customres) using the shim.

**Comment by mumoshu** [comment]
@fsenart Thanks! I'm still looking forward to tackle this. I'll certainly try aws-lambda-go-shim at first.

**Comment by mumoshu** [comment]
Just a quick note - probably we can manage the following deployments in custom cfn resources:

- kube-dns
- kube-dns-autoscaler
- cluster-autoscaler
- kube-resources-autosave
- heapster
- kubernetes-dashboard
- tiller

The following deployments won't fit in custom resources:

- calico (requires custom templating on controller nodes)

**Comment by mumoshu** [comment]
I believe that this idea had been considered so nice at the time of writing because we were to rely on CloudFormation (and Nested Stacks) for making entire update process to be reliable. Ctrl-C'ing kube-was doesn't interrupt an cluster update in the middle of process.

However, given the context that we're heading towards the world without nested stacks as per #1112, I guess this should be reconsidered.

>  - All controllers unnecessary need to be rolled when manifest updates which is slow.
> - Resources which used to be installed, but not anymore remain hanging in existing clusters
> - Any future CF ChangeSet preview we implement makes diff hidden

All these benefits themselves can be resolved by just doing it client-side.
More concretely:

1. separating manifests used in install-kube-system out of cloud-config-controller, and 
2. maybe the first install would be done from controller userdata but
3. subsequent updates are made from client-side, for example kube-aws shell-out to kubectl

Sounds like it would make cluster update even less reliable?
Yes, it would.

However, what I believe is that we eventually need a "Kubernetes-free, kube-aws operator" to bring back all the reliability provided by CloudFormation Nested Stacks.
We could utilize anything including Lambda to implement the operator thing.
