### ISSUE TITLE
Implement fast worker roll

### ISSUE THREAD

**Issue by redbaron** [kubernetes-incubator/kube-aws#908]
Once last static pod on worker moves to daemonset, it opens road to a relatively straightforward "fast worker roll". Idea is to pull kubelet systemd config from publically available "kube-public" namespace (no auth needed) configmap. This would allow kubelet update without restarting worker nodes and reshuffling any pods. (new pods will be simply discovered).

To make it happen need to solve:
 - [ ] replace kubelet systemd unit with "unit downloader" + systemd daemon reload. Alternatively just kubelet-wrapper params + env vars should be downloaded, then there is no need for systemd daemon reload which known to have problems
 - [ ] figure out how to coordinate pull so that only X instances do it at a time, not all of them
 - [ ] figure out how to report success and rollback in case of errors.

**Comment by mumoshu** [comment]
Perhaps we can use a similar infrastructure to this - which updates kubelets' configuration without rolling-updating nodes - to update TLS assets fast enough not reshuffling nodes or evicting pods due to long(>pod eviction threshold) apiserver<->kubelet disconnectivity due to node rolling?

**Comment by mumoshu** [comment]
> figure out how to report success and rollback in case of errors.

I had imagined that we could make the unit-downloader a daemonset so that we can utilize the RollingUpdate strategy of daemonsets for the coordination.

However, what I'm unsure then is that how an unit-downloader reports a failure when it completely broke the kubelet on the node. The unit-downloader would be unable to report without a running kubelet, of course?
Would implementing our own health-checking & roll-back mechanism on the unit-downloader specific to kubelets would resolve it?

**Comment by mumoshu** [comment]
@redbaron Was this mainly intended to ease upgrading K8S version? Or do you like to support frequent updates to kubelet configs?

**Comment by redbaron** [comment]
Yes. Main benefit is that if your workers are self-hosted, all you need is to run kubelet with right config and right certificates. All these pieces are easily downloadable.

Once done, you can have cluster upgrades without pods migration and no downtimes to your workers

**Comment by mumoshu** [comment]
@redbaron Thanks. Seems like I finally managed to catch it 😃 

Btw, does this imply that we need a another way different than a cloudformation update to trigger a worker roll for this case?
I imagine something like `kube-aws update kubelets` or alike?

**Comment by redbaron** [comment]
Download itself can be just  `curl | jq` from some configmap in kube-public namespace, where no authentication needed (or you can grant user in kubelet cert/token perms to  download particular configmap) or it can be S3 bucket download. 

Main problem is how to check for success, report errors  and abort

**Comment by mumoshu** [comment]
@redbaron Thanks!

So I suppose for example a privileged daemonset which mounts `/etc/kubernetes/manifests` could somehow get/write the updated kubelet systemd config(with `curl | jq`, or even just `cat` from a configmap vol or anything).

Maybe we can just configure the daemonset to use `updateStrategy: RollingUpdate` plus a label with the checksum of configmap content as its value so that configmap update triggered via kube-aws would result in a worker roll.

Yes, we also need to consider error reporting and abort on error things. A readiness check in the daemonset which checks for the status file to see if the write to systemd config succeeded or not would help here?

Slightly relevant, inspiring issue: https://github.com/kubernetes/kubernetes/issues/36601

**Comment by mumoshu** [comment]
And we could trigger `systemd daemon-reload` from either systemd unit watches the timestamp of the config file or a "reload trigger" file which can be written by the daemonset pod.
Would it be possible to mount an unix socket for communication with systemd so that we could run `systemctl daemon-reload` from inside a container?
