### ISSUE TITLE
Switch to NLB instead of ELB

### ISSUE THREAD

**Issue by redbaron** [kubernetes-incubator/kube-aws#937]
Main benefit: stable IP addresses within VPC, therefore it is expected to be much less broken TCP connections when AWS roll underneath infrastructure

**Comment by mumoshu** [comment]
@redbaron Thx!
I'm really wanting to switch to NLB - in other words enable NLB by default - rather than adding it as an optional feature.
https://github.com/kubernetes-incubator/kube-aws/issues/598#issuecomment-330217564 reported by @danielfm today strengthened the idea.
WDYT?

Btw, anyway, we need to keep the support for ELB for the China region because NLB has
not available there yet.

**Comment by danielfm** [comment]
Maybe this should be added as an optional feature via a `type` parameter to `apiEndpoints[].loadBalancer`; this would allow users to migrate towards the new NLBs without the need to re-create the whole cluster by:

1. Change `cluster.yaml` to add a new API endpoint of type `network`, leaving the other endpoint intact
2. Run `kube-aws update` to create the new load balancer while leaving the old one intact
3. Change `worker.apiEndpointName` to the new load balancer
4. Run `kube-aws update` to make update all workers to use the new endpoint
5. Change `cluster.yaml` to remove the old load balancer
6. Run `kube-aws update` to remove the now unused load balancer
