### ISSUE TITLE
0.9.8 darwin release has a dirty tag

### ISSUE THREAD

**Issue by jyoungs** [kubernetes-incubator/kube-aws#949]
Not sure this is a problem, but why does the "official" release have a dirty flag?

```bash
> bin/kube-aws version
kube-aws version v0.9.8+dirty
```

**Comment by adyromantika** [comment]
Would like to add that the linux binary also has the dirty flag.

**Comment by c-knowles** [comment]
@jyoungs sorry about that, it should not be marked as dirty. Something likely went wrong with the publishing process as `+dirty` means the source being built has diverged from the git tag. Since there are now newer releases with this fixed, I'm going to close this out. If you still need v0.9.8 please do let us know and maybe @mumoshu can re-publish it somewhere.
