### ISSUE TITLE
Cluster master send api call to terminate instance in an exist autoscaling group

### ISSUE THREAD

**Issue by zhangtiny123** [kubernetes-incubator/kube-aws#989]
Hi ，

I'm running a k8s cluster created by kube-aws of version  ```0.9.8```,
and I have an existing autoscaling group ,
I changed the desired instance count of the existing autoscaling group from 5 to 7 maybe.
But then an api call from the k8s cluster master sent to aws and terminated the new instance... 

From CloudTrail I found that 
```
"requestParameters": {
        "shouldDecrementDesiredCapacity": true,
        "instanceId": "instance-id-of-the-master-node"
    }

# from response 
"cause": "At 2017-10-17T05:47:21Z the instance was taken out of service in response to a user request, shrinking the capacity"
```

**Comment by mumoshu** [comment]
@zhangtiny123 Hi, thanks for using kube-aws 👍 
Probably you've enabled CA on your cluster and unfortunately encountered #800?
You should also increase `MinSize` so that CA won't try to scale down your cluster in the first place.
You would also need to fix your cluster.yaml according to https://github.com/kubernetes-incubator/kube-aws/issues/800#issuecomment-325965541 so that autoscaling is actually enabled on one or more node pool(s).

**Comment by zhangtiny123** [comment]
@mumoshu 
Yes, it's the same issue as #800 , sorry for the duplicate report,  I don't find that...
Thanks for your help. 👍 👍 👍
